### ISSUE TITLE
Margin size and simple/extended approach documentation

### ISSUE THREAD

**Issue by pnrobinson** [TheJacksonLaboratory/Gopher#105]
@hansenp 
Please check the definitions of simple and extended approach here.

http://vpv.readthedocs.io/en/latest/setup.html

Also, it would be good to have a graphic about the margin size and to define exactly what we need. Can you adapt the graphic you made recently for this?
Maybe we should put the definitions for all of the settings on a separate page?

**Comment by hansenp** [comment]
The definitions of the simple and extended approach were okay. I added figures for the two approaches.

Furthermore, I added sections for margin size and tiling factor.

I would suggest to collect a detailed parameter description on this page, and maybe have a second page with short descriptions in table format?

**Comment by hansenp** [comment]
This comment arose from issue #63. There is a dependency between the average fragment length in the sequencing library and the distribution of 5' ends of reads around restriction enzyme cutting sites, i.e ends of fragments. See also issue #63 and manuscript.

250 bp seems to be good choice for the default, but we should add more documentation in readthedocs about this.

**Comment by hansenp** [comment]
The figure for the extended approach here:

http://vpv.readthedocs.io/en/latest/setup.html

is not correct anymore and needs to be adjusted. For the current implementation all fragments must be within the interval [TSS-upSize;TSS+downSize].

**Comment by pnrobinson** [comment]
@hansenp 
http://gopher.readthedocs.io/en/latest/setup.html#simple
do we still need to fix this? It looks like the upstream is overlapping --this is what you mean, right?

**Comment by hansenp** [comment]
What I meant was that for the implementation of the extended all fragments had to be _completely_ within the interval [TSS-upSize;TSS+downSize]. In the figure for the extended approach the fragments only _partially_ overlap the interval [TSS-upSize;TSS+downSize].

![image](https://user-images.githubusercontent.com/10495485/39809182-65545f32-5381-11e8-9e2f-c7a22867c7bc.png)

However, we changed the approach afterwards (#121) and now the figure is correct. I will close this issue.
