### ISSUE TITLE
Enable import of probes/baits into VPV

### ISSUE THREAD

**Issue by hansenp** [TheJacksonLaboratory/Gopher#113]
Once probe are designed for target regions by an external program such as Agilent's SureDesign wizard it might be useful to be able to import the probes into VPV. Then we could check for probes outside target regions and annotate each target region with the number of probes. This information could be used later for normalizing the sequencing data.

**Comment by pnrobinson** [comment]
So this would be a BED file I guess? Probably we need this in diachromatic and not VPV/VPC. Do we have an example file we could use to set up the parser and some tests?

**Comment by hansenp** [comment]
We have a probe file for the last CD4 panel. Here only the first lines:

```
TargetID	ProbeID	Sequence	Replication	Strand	Coordinates
CD274_1	BA_326301_000000	AGTAGATCTAAGTATTTTTTCATGAAACTTGTTGTACATGTGTGTGTCATACACAGACTATATATATGCAGTACCTGTAAACTGTATTGCCACATAATGTCTATATTTTCCTAGAGGTCA	1	+	chr9:5449079-5449198
CD274_1	BA_326301_000001	AAACTTGTTGTACATGTGTGTGTCATACACAGACTATATATATGCAGTACCTGTAAACTGTATTGCCACATAATGTCTATATTTTCCTAGAGGTCACAGTCACCAAAGTTGGGAAGTCAC	1	+	chr9:5449103-5449222
CD274_1	BA_326301_000002	ATACACAGACTATATATATGCAGTACCTGTAAACTGTATTGCCACATAATGTCTATATTTTCCTAGAGGTCACAGTCACCAAAGTTGGGAAGTCACCCAACTTCGGGAACTTTGGGAAGT	1	+	chr9:5449127-5449246
CD274_1	BA_326301_000003	ACCTGTAAACTGTATTGCCACATAATGTCTATATTTTCCTAGAGGTCACAGTCACCAAAGTTGGGAAGTCACCCAACTTCGGGAACTTTGGGAAGTCACCCAAACTTACAGTCACCAAAA	1	+	chr9:5449151-5449270
CD274_1	BA_326301_000004	ATGTCTATATTTTCCTAGAGGTCACAGTCACCAAAGTTGGGAAGTCACCCAACTTCGGGAACTTTGGGAAGTCACCCAAACTTACAGTCACCAAAATTGCTCTATTCTACTATGTGACCT	1	+	chr9:5449175-5449492
```
Shall I upload the entire file (8 Mb) to _src/test/resources_, or do you think it would be better to create a toy example?

**Comment by pnrobinson** [comment]
I am wondering whether we shouldn't just use this file for diachromatic? What exactly would we do in VPV?

**Comment by hansenp** [comment]
For example, one could annotate the viewpoints or selected fragments with the corresponding number of probes. This information could be used downstream for normalization. However, we do not know anything about the influence on enrichment.

In the medium term, we should think about designing the probes within VPC. This would be much more convenient for users, and maybe it is not too difficult to implement.

**Comment by hansenp** [comment]
Yes, one could also annotate the fragments with the probe numbers in _diachromatic_ during digestion.

**Comment by hansenp** [comment]
I added two probe files that can be used for the development of probe import into GOPHER. The files correspond to the two CD4 panels:

1. `ImmunePanelCD4_5x_PLUS_PDL1_1_Probes.txt`
2. `cd4v2_021318_1_Probes.txt`

The coordinates are for hg19.

The first probe design was done using the SureDesign wizard. The probe file was obtained via email (informatics_support@agilent.com) upon request. The probe design ID has to be indicated. Delays of up to three weeks are possible. The format looks as follows:
```
TargetID	ProbeID	Sequence	Replication	Strand	Coordinates
CD274_1	BA_326301_000000	AGTAGATCTAAGTATTTTTTCATGAAACTTGTTGTACATGTGTGTGTCATACACAGACTATATATATGCAGTACCTGTAAACTGTATTGCCACATAATGTCTATATTTTCCTAGAGGTCA	1	+	chr9:5449079-5449198
CD274_1	BA_326301_000001	AAACTTGTTGTACATGTGTGTGTCATACACAGACTATATATATGCAGTACCTGTAAACTGTATTGCCACATAATGTCTATATTTTCCTAGAGGTCACAGTCACCAAAGTTGGGAAGTCAC	1	+	chr9:5449103-5449222
CD274_1	BA_326301_000002	ATACACAGACTATATATATGCAGTACCTGTAAACTGTATTGCCACATAATGTCTATATTTTCCTAGAGGTCACAGTCACCAAAGTTGGGAAGTCACCCAACTTCGGGAACTTTGGGAAGT	1	+	chr9:5449127-5449246
CD274_1	BA_326301_000003	ACCTGTAAACTGTATTGCCACATAATGTCTATATTTTCCTAGAGGTCACAGTCACCAAAGTTGGGAAGTCACCCAACTTCGGGAACTTTGGGAAGTCACCCAAACTTACAGTCACCAAAA	1	+	chr9:5449151-5449270
```
The second design was created by Agilent's 'quikdesign team'. It has to be indicated that the file for probes is required. Then it can be downloaded from a shared collaboration directory that can be accessed through the SureDesign homepage. The format looks as follows:
```
TargetID	ProbeID	Sequence	Replication	Strand	Coordinates
chr1	probe_011718_hg19_chr1_1139794	AGTGGCCTTCGTGGCCCCCGGAGAAGGTCCCCGAGGCACAGTCGATACACTGGAAGCCAAAACTGAATTTCCCTGGTGTGGGGTGTGGGGGGAGGGAGGGAGGGAGGCTGGTGGAGTTGC	1	+	chr1:1139795-1139914
chr1	probe_011718_hg19_chr1_1141481	TGGAACAGCCGTCCTCCACCTCCAGACCCCAGACCCCTCTTGAGGGCGCTCCCACCTGGCTCACCCCTGCTCCCGGCCGGGGCCACTGGCTGGAGCTGGCACACCTCCGCCTCCCTCTGG	2	+	chr1:1141482-1141601
chr1	probe_011718_hg19_chr1_1141731	CCGGTCCGCGTTAAGTAAACGCGGTTTACTTACCCGGGTAATCGCGGCAGCAGCGCGTCGTGTGAACCCGGCAGCAGCGCGCGTCCGTTCCCGTCCCAAGCAGGAGGCGCCCAGGGCCGC	2	+	chr1:1141732-1141851
chr1	probe_011718_hg19_chr1_1142032	GTTCATGACCTGAGAATCCCGACCCAGGTGAAGTGCGTGTGAGGAGGGGGTGTAGACACTGCGGACACAGCCCGGTCCCCCGCAGGTCGCCGGCAGGGGCGGGGAAACCAGGCTGGCGGG	2	+	chr1:1142033-1142152
```
Note that the target IDs for the two files differ. For the first file the target IDs equal the IDs of target regions that were uploaded to the SureDesign wizard. For the second file chromosome names are used as target IDs.

**Comment by hansenp** [comment]
The content of the bigwig file for _Alignability_ and 100mer looks as follows:
```
chr1    10000   10014   0.00277778
chr1    10014   10015   0.333333
chr1    10015   10026   0.5
chr1    10026   10031   1
chr1    10031   10036   0.5
```
I the documentation the scores are explained as follows:

> The CRG Alignability tracks display how uniquely k-mer sequences align to a region of the genome. ... For each window, a mappability score was computed (S = 1/(number of matches found in the genome): S=1 means one match in the genome, S=0.5 is two matches in the genome, and so on).

**Comment by hansenp** [comment]
I think the scores are appropriate for our purposes. @pnrobinson: What do you think?

We could prepare an alignability map for 120mers or use the one for 100mers downloadable at UCSC as a compromise for practical reasons. 

We will need to transform the bedgraph (https://genome.ucsc.edu/goldenpath/help/bedgraph.html) file into a data structure that supports the following operation:

`double getScoreAtPos(String chrom, int probePos)`

This could be done using a hash map and two java arrays for each chromosome. The keys of the hash map would be the chromosome names, and they would point to an pair of arrays of equal size that corresponds to the number of lines for the given chromosome. The first array contains the already sorted positions from column two and the second array the corresponding scores from column four.

Given a position `probePos` the array could be searched for the associated index using binary search (https://docs.oracle.com/javase/7/docs/api/java/util/Arrays.html#binarySearch(byte[],%20byte)). The index can then be used to find the associated score in the second array.

**Comment by pnrobinson** [comment]
@hansenp  -- is this item still active or should we close it?

**Comment by hansenp** [comment]
Because Gopher is able to create baits, we can close this issue. Maybe import of baits is an interesting feature but this would be a bit complex to implement. Then the selection of digests would depend on the imported baits, i.e. the current mechanism for bait selection would need to be bypassed somehow. This is too much work for now. Therefore, I will close this issue.
