### ISSUE TITLE
Rename software from Viewpoint viewer to Viewpoint creator

### ISSUE THREAD

**Issue by hansenp** [TheJacksonLaboratory/Gopher#116]
Since the software creates viewpoints the name Viewpoint creator (VPC) seems to be more suitable.

It would also be nice to have something like a logo when the software is started.

**Comment by pnrobinson** [comment]
Maybe we can come up with an even catchier name?

**Comment by hansenp** [comment]
Amazon is also using the acronym VPC (https://aws.amazon.com/vpc/). I'm sure there is definitely no catchier name for our software ;)

I will start to think about a logo. Maybe something similar to this?

![image](https://user-images.githubusercontent.com/10495485/36532465-b890ca5a-17b8-11e8-8008-c78d6294ca2f.png)

Combined with looping and DNA?

**Comment by hansenp** [comment]
GOPHER: Generator Of Probes for capture Hi-c ExpeRiments

<img width="678" alt="screen shot 2018-03-20 at 6 40 06 pm" src="https://user-images.githubusercontent.com/10495485/37686514-32ace9bc-2c6e-11e8-82a1-0964ca90f577.png">

**Comment by hansenp** [comment]
There is already software with the name GOPHER:

https://www.gophersoftware.com/

@pnrobinson: Does this pose a problem?

**Comment by pnrobinson** [comment]
This does not pose a legal problem because the area of use is completely different.
We could also just name Viewpoint Gopher (short: "VG") ?

**Comment by pnrobinson** [comment]
We are now good to go with GOPHER!

**Comment by hansenp** [comment]
Sorry, but I have to reopen this issue. VPV still occurs in many places.
![image](https://user-images.githubusercontent.com/10495485/39806131-64c90124-5379-11e8-9b3c-57cb41dee9a5.png)
![image](https://user-images.githubusercontent.com/10495485/39806221-a349cab4-5379-11e8-8a63-236b5a26aca0.png)
![image](https://user-images.githubusercontent.com/10495485/39806265-beb3eb0e-5379-11e8-9d72-8a04a6624a7b.png)
![image](https://user-images.githubusercontent.com/10495485/39806297-d5ab9a82-5379-11e8-9dbd-662a6d2d0609.png)
![image](https://user-images.githubusercontent.com/10495485/39806325-f02f19ba-5379-11e8-8fb3-f1189d3be05e.png)

This issue should have low priority. To begin with, we can replace VPV with Gopher whenever we see it.

**Comment by pnrobinson** [comment]
Ups -- I think I got all instances this time!

**Comment by hansenp** [comment]
I've found another instance:

<img width="601" alt="screen shot 2018-07-22 at 7 57 30 am" src="https://user-images.githubusercontent.com/10495485/43045335-206fdb60-8d85-11e8-9007-58ab4633ccb2.png">

**Comment by pnrobinson** [comment]
I think I have now removed really all references to VPV Gui!
