### ISSUE TITLE
Revise URL string to show all selected enzymes

### ISSUE THREAD

**Issue by pnrobinson** [TheJacksonLaboratory/Gopher#118]

**Comment by pnrobinson** [comment]
@hansenp  Can you provide an example URL for this? Somehow I have not been able to find the documentation

**Comment by hansenp** [comment]
In UCSC's genome browser click on _Mapping and Sequencing > Restr Enzymes_. There is a text field in which a comma separated list of enzymes can be entered. I entered `DpnII,HindII`.

This is the URL:
https://genome-euro.ucsc.edu/cgi-bin/hgTracks?db=hg38&lastVirtModeType=default&lastVirtModeExtraState=&virtModeType=default&virtMode=0&nonVirtPosition=&position=chr4%3A190183699%2D190184160&hgsid=226909998_LR21eCNiBAYjbPDbepxrw2CF1eqx

**Comment by pnrobinson** [comment]
The URL gets changed and so the one you pasted in is not the one that we would construct with the code. Here is an example of my problem:

http://genome.ucsc.edu/cgi-bin/hgTracks?db=hg38&position=chr4:190183699-190184160&pix=1000gc5Base=dense&snp150Common=hide&gtexGene=hide&dgvPlus=hide&pubs=hide&knownGene=hide&refGene=full&oligoMatch=pack&hgt.oligoMatch=ACGT,GCCTAA

THere are two restriction enzymes: ACGT and GCCTAA. However, if I pass thus URL, then the browser shows "Perfect matches to short sequence ACGTGCCTAA, i.e., it pastes both strings together...

**Comment by hansenp** [comment]
I think the track name is `cutters`.

**Comment by pnrobinson** [comment]
http://genome.ucsc.edu/cgi-bin/hgTracks?db=hg38&position=chr4:190183699-190184160&pix=1000gc5Base=dense&snp150Common=hide&gtexGene=hide&dgvPlus=hide&pubs=hide&knownGene=hide&refGene=full&oligoMatch=pack&cutters=ACGT;GCCTAA

-- still does not work!

**Comment by hansenp** [comment]
By default all enzymes are shown, if the display mode is `full`. The enzymes can be filtered by a comma separated list of enzyme name such as `DpnII,HindIII`. But I don't know how to add additional attributes of a track to the URL.

**Comment by pnrobinson** [comment]
@hansenp -- could you provide an example of an URL that works -- please do not copy from browser, the UCSC Genome Browser changes the original URL. I cannot get this to work.

**Comment by hansenp** [comment]
This works for me:

http://genome.ucsc.edu/cgi-bin/hgTracks?db=hg19&position=chr9%3A14397282-14405058&cutters=full&hgt.cutters=HindIII,DpnII

**Comment by pnrobinson** [comment]
Finally! Now this works!!
