### ISSUE TITLE
Regulatory exome: Filter out duplicated entries.

### ISSUE THREAD

**Issue by hansenp** [TheJacksonLaboratory/Gopher#124]
Testing of the _regulatory exome_ feature (#123) has shown that has shown that there are duplicated entries for exons of overlapping trancripts. Here an example:

![image](https://user-images.githubusercontent.com/10495485/34990082-b330e46e-fabc-11e7-9054-ed329f852a57.png)

Those region should be filtered out.

**Comment by pnrobinson** [comment]
I have implemented a feature to remove exact duplicates. There are still some overlapping areas, but I think that we can leave it to the user to use BEDtools to merge these entries if desired. I have added this to the documentation of VPV.
http://vpv.readthedocs.io/en/latest/ see new section on Regulatory

@hansenp please check this and close issue if all is OK!

Note -- code is on development branch, but I will merge back to master today
