### ISSUE TITLE
Test testInitialization() in ViewPointPresenterTest fails

### ISSUE THREAD

**Issue by hansenp** [TheJacksonLaboratory/Gopher#134]
The following test

```
    /**
     * Test that the controller was properly initialized. E.g. that it contains model, ViewPoint, etc.
     *
     * @throws Exception
     */
    @Test
    public void testInitialization() throws Exception {
        Thread.sleep(4000); // just show the screen for now.
    }
```

fails with the error message

`Class not found: "vpvgui.gui.viewpointpanel.ViewPointPresenterTest"Empty test suite.`

if the directory target created with `mvn package` is not present.

If I build package with `mvn package` successfully and rerun the test, I get the following error message:

```
java.lang.RuntimeException: java.util.concurrent.ExecutionException: javafx.fxml.LoadException: 
/home/peter/IdeaProjects/VPV/target/test-classes/fxml/viewpoint.fxml
```

**Comment by pnrobinson** [comment]
I do not understand what this test is supposed to do. Also, it is probably not a good idea to have fxml files in the test hierarchy. Any test should have some Assert.assertSomething(ABC) in it -- otherwise it is not actually testing anything.

**Comment by hansenp** [comment]
I cannot remember that I have written this test either.

**Comment by hansenp** [comment]
Maybe Daniel?

**Comment by pnrobinson** [comment]
let's delete it then

**Comment by pnrobinson** [comment]
I have deleted this test class -- I do not think we need it since we can see the GUI is starting, and I cannot get the test class to run...
