### ISSUE TITLE
VPC displays incorrect number of target genes

### ISSUE THREAD

**Issue by hansenp** [TheJacksonLaboratory/Gopher#141]
If save and reopen a project the information about target genes and viewpoints changes. This is before saving:

![image](https://user-images.githubusercontent.com/10495485/37597988-dffdaf94-2b78-11e8-9598-e1f4925e5cad.png)

If reopen the project it says there are 583 target genes, and the number of viewpoints is not displayed anymore.

![image](https://user-images.githubusercontent.com/10495485/37598884-61137724-2b7b-11e8-9b11-5defdadf34c0.png)

**Comment by pnrobinson** [comment]
Fixed this!
