### ISSUE TITLE
 Refactor IO so that the multi-FASTA file includes non-canonical chromosomes

### ISSUE THREAD

**Issue by hansenp** [TheJacksonLaboratory/Gopher#143]
Refactor IO so that the multi-FASTA file includes non-canonical chromosomes because the same file is used for Diachromatic.

But the non-canonical chromosomes should not be used for viewpoint creation because there were issues with genes on these chromosomes (#59, #60).

**Comment by pnrobinson** [comment]
I have refactored this--the multiFASTA file now includes all chromosomes, canonical or non-canonical.
@hansenp We will need to filter the ViewPoint creation to include just the canonical chromosomes, right? In this case, I see you have added code assignVPVGenesToChromosomes -- should that be the best place to do this?

**Comment by hansenp** [comment]
I cannot remember that I have added code for `assignVPVGenesToChromosomes`. Could you provide some more information? In which class?

**Comment by hansenp** [comment]
@pnrobinson I would need more information about `assignVPVGenesToChromosomes` to follow this up.

I don't think that Gopher can create viewpoints for non-canonical chromosomes because those are skipped when the refGene file is parsed in class `RefGeneParser`.

<img width="863" alt="screen shot 2018-06-08 at 6 23 23 am" src="https://user-images.githubusercontent.com/10495485/41153575-20c0c984-6ae5-11e8-8c15-178808f2cf6c.png">

**Comment by pnrobinson** [comment]
The current parser should include all chromosomes but the viewpoint creator ignores non-canonical chromosomes. This let's us use the chromosome file for diachromatic so that bowtie2 can map to non-canonical if it so chooses.

**Comment by pnrobinson** [comment]
@hansenp  If we wanted to offer an option to make probes for non-canonical chromosomes, I think this would be easy, but I am not sure it would be a useful feature unless somebody asks for it. Can we close this issue, or do you see a need for non-canonical probes at this stage?

**Comment by hansenp** [comment]
But I still do not understand the 1 bp gaps between fragments.
