### ISSUE TITLE
Create file for digested fragments that can be used as input for Diachromatic

### ISSUE THREAD

**Issue by hansenp** [TheJacksonLaboratory/Gopher#144]
The digestion of the genome is currently implemented within Diachromatic. However, there are some bugs and shortcomings.

TheJacksonLaboratory/diachromatic#32
TheJacksonLaboratory/diachromatic#33
TheJacksonLaboratory/diachromatic#40

Furthermore, the counting of read pairs between interacting fragments (TheJacksonLaboratory/diachromatic#35) requires information about active and inactive fragments, which is not available within Diachromatic.

Within GOPHER all informations about restriction fragments such as GC and repeat content, fragment lengths etc. are available. Therefore, the creation of the digest file should be implemented in GOPHER. The digest file can be seen as the interface between GOPHER and Diachromatic.

This issue is solved, if GOPHER creates a digest file with the following columns:

1.  Chromosome
2.  Fragment_Start_Position
3.  Fragment_End_Position
4.  Fragment_Number (why is this useful?)
5.  5'_Restriction_Site
6.  3'_Restriction_Site
7.  Length
8.  GC content of margins (upstream;downstream)
9.  Repeat content of margins (upstream;downstream)
10. Number of probes (upstream;downstream)
11. Active/Inactive flag

**Comment by hansenp** [comment]
For our goal to make a release of Gopher this issue is maybe not that important. However, Diachromatic and the idea with the Poisson regression (TheJacksonLaboratory/diachromatic#21) depend on this feature.

Furthermore, I noticed that there are invalid records in the digest file produced by Gopher (TheJacksonLaboratory/diachromatic#40). Because of this and the fact the entire downstream analysis depends on the digest file, I will label this issue with _bug_ and _High Priority_.

**Comment by pnrobinson** [comment]
@hansenp  check out prototype digest export -- but the function for finding active fragments is not working yet.
Todo-- also make sure we export the chromosomes in canonical order.
@hansenp  -- should we include non-canonical chromosomes in the digest file?

**Comment by hansenp** [comment]
Yes, I think we should include non-canonical chromosomes. Since we are using them for mapping there will be potentially read pairs from non-canonical chromosomes, which could cause difficulties , if the corresponding digests are not available.

**Comment by hansenp** [comment]
I created digest files for HindIII with Gopher and HiCUP. Both files contain the same number of digests. However, the coordinates are shifted by one, whereby the coordinates for HiCUP are smaller.

```
==> Digest_hg19_HindIII_hicup.bed <==
chr1	1	16007
chr1	16008	24571
chr1	24572	27981
==> hg19_hindIII_digest_gopher.bed <==
chr1	1	16008
chr1	16009	24572
chr1	24573	27982
```
The first and last coordinates of the chromosomes are identical for HiCUP and Gopher.

Here is a screenshot from IGV:

![image](https://user-images.githubusercontent.com/10495485/41233700-7e0a8952-6d8a-11e8-8964-d02914daa365.png)

The upper track is for HiCUP and the lower track is for Gopher. I think the coordinates for HiCUP are more correct. However, I do not understand why there is a gap of 1 bp between fragments. @pnrobinson Do you know why?

**Comment by hansenp** [comment]
I changed the line in class `DigestCreationTask`

`int pos = matcher.start() + offset + 1; /* one-based position of first nucleotide after the restriction enzyme cuts */`


to 

`int pos = matcher.start() + offset;`

Now Gopher and HiCUP produce identical digests for hg19.

**Comment by hansenp** [comment]
But I still do not understand the 1 bp gaps between fragments.

**Comment by pnrobinson** [comment]
The 1+ is necessary for the fragments to be found in the binary tree -- the HTSJDK is using one-based numberings and here we have Java strings with 0-based numbers. I thought that we previously checked whether our numbers are correct and were happy. Let's check again though.

**Comment by pnrobinson** [comment]
If you look in the digest output file, you should see the same number of T's as you have selected fragments. On my machine, this number was zero unless I adjusted by "+1". 
We also need to figure out where the gaps are coming from.

**Comment by hansenp** [comment]
Sorry, I made mistake yesterday. When I converted the digest files, which are one based, to BED format, which is 0-based, I forgot to subtract 1 bp from the start and end coordinates. Now (after the bug fix) it looks in IGV as follows:

<img width="352" alt="screen shot 2018-06-12 at 3 40 38 am" src="https://user-images.githubusercontent.com/10495485/41276502-696fa438-6df2-11e8-8aa4-2f35be63aa93.png">

IGV has 1-based coordinates. The start positions of the fragments are displayed correctly. However, the end positions are not. This is the content of the BED file imported to IGV:

```
$ head Digest_hg19_HindIII_None_03-00-54_12-06-2018.bed
chr1	0	16006
chr1	16007	24570
chr1	24571	27980
```
IGV adds 1 bp to the start positions but not to the end positions. This is the explanation for the 1 bp gap. The content of the digest files produced by _HiCUP_ and _Diachromatic_ are without gaps and they seem to be correct.

**Comment by hansenp** [comment]
I'm able to reproduce the bug with active fragments not reported as active in the exported digest file. I'm using the 32 example genes for human in Gopher. For

`int pos = matcher.start() + offset;`

I get zero fragments reported as active in the digest file. And with

`int pos = matcher.start() + offset + 1;`

I get 80 fragments reported as active.

**Comment by hansenp** [comment]
If I switch back to

`int pos = matcher.start() + offset + 1;`

then we have `Digest` objects with 1-based coordinates in `fraglist`, and these coordinates correspond to starting positions of fragments.

Since we are 1-based I changed

`Integer previousCutPosition=0; // start of chromosome`

to

`Integer previousCutPosition = 1; // start of chromosome`

Since the coordinates of the `Digest` objects correspond to starting positions of fragments I changed at the beginning of the for loop

```
            int startpos= (previousCutPosition+1);
            int endpos = f.position; 
```

to

```
            int startpos= previousCutPosition;
            int endpos = f.position - 1;  // f.position is the 1-based first coordinate of the next fragment
```

and at the end of the for loop I left the assignment unchanged

`            previousCutPosition = f.position;`

because this is the correct starting position of the next fragment.

Then I counted the occurrences of "T" and "F" within the exported digest file:
```
$ cat hg19_HindIII_digests_gopher_4.txt | tail -n+4 | awk '{print $12}' | sort | uniq -c
837565 F
  80 T
```
80 fragments are reported to be active. However, in the column for selected fragments within the GUI I count 125. And also the function `vp.getActiveSegments();` returns a list with 125 segments.

Maybe this inconsistency is due to the `btree`.

**Comment by pnrobinson** [comment]
If HindIII A^AGCTT gets transformed to A + AGCT + AGCT + T = AAGCTAGCTT then essentially we never see the nucleotides in sqaure brackets in reads [A]AGCT[T] -- these nucleotides exist in the genome, otherwise we would not have cut, but they are removed from the reads by the process of Hi-C. 
@hansenp  can this be the reason for the gaps?

**Comment by hansenp** [comment]
I think the problem with the gaps is solved. The exported regions do not have gaps. The gaps seem to be introduced by IGV (see above).

> GV adds 1 bp to the start positions but not to the end positions. This is the explanation for the 1 bp gap. The content of the digest files produced by HiCUP and Diachromatic are without gaps and they seem to be correct.

**Comment by pnrobinson** [comment]
IGV is probably expecting UCSC type numbering. For example the first three nucleotides would be (0,3); and the next three nucleotides  would be (3,6)
One based numbering is (1,3) and (4,6)
-- so it is still strange the IGV has a gap

**Comment by hansenp** [comment]
I will never understand this. This is the definition of BED coordinates from UCSC:

>  chromStart - The starting position of the feature in the chromosome or scaffold. The first base in a chromosome is numbered 0.

> chromEnd - The ending position of the feature in the chromosome or scaffold. The chromEnd base is not included in the display of the feature. For example, the first 100 bases of a chromosome are defined as chromStart=0, chromEnd=100, and span the bases numbered 0-99.

Maybe I can remember it like this: For the BED format, the start coordinates are 0-based end the end coordinates are -1-based. Would this be correct?

However, our as well as the digest file produced by HiCUP are not BED format. The start and end coordinates are 1-based. I think everything is correct.

**Comment by hansenp** [comment]
There is also no inconsistency with the number of active/selected fragments. The 125 are not unique. The unique number of selected is 80.

I think the export works now. The numbers of probes are still missing. We will have to add this as soon as these numbers are available.

**Comment by hansenp** [comment]
This feature is now implemented. I created a separate issue for the numbers of probes ( #180). I will close this issue.
