### ISSUE TITLE
Class GopherException is missing

### ISSUE THREAD

**Issue by hansenp** [TheJacksonLaboratory/Gopher#150]
The custom exceptions of Gopher extend the class `GopherException`.

![image](https://user-images.githubusercontent.com/10495485/41224315-741714ce-6d6c-11e8-8f50-a2f95b9ebbaf.png)

However, there is no such class.

![image](https://user-images.githubusercontent.com/10495485/41224355-8f1f05d8-6d6c-11e8-81b7-b6e2aa527c6c.png)

**Comment by hansenp** [comment]
I added a exception class with the following content:

![image](https://user-images.githubusercontent.com/10495485/41224478-e04063bc-6d6c-11e8-9faf-43d242124595.png)

I'm not sure if this is enough/correct. @pnrobinson Could you please check?

**Comment by pnrobinson** [comment]
The code is correct, but maybe add what the use-case is. There are lots of ways for an integer to be out of bounds?

**Comment by hansenp** [comment]
Sorry this was the wrong file. Today I added this here:

![image](https://user-images.githubusercontent.com/10495485/41229517-961cc95a-6d7c-11e8-95df-8ae9577eaa9d.png)

I.e. the super class for all Gopher exceptions. This was missing.

**Comment by pnrobinson** [comment]
The CTOR with the Throwable is optional but can be added -- no harm done!
