### ISSUE TITLE
Setup tab

### ISSUE THREAD

**Issue by pnrobinson** [TheJacksonLaboratory/Gopher#160]
Setup tab
======

Change text field for Maximum repeat content (%) to
Maximum average kmer alignability. Refactor the
underlying variable to akaMax.

Leave the text fields for minimum and maximum GC as
they are but change the default for the minimum GC
content from 25% to 35%. In future, these thresholds will
be applied to probes and not to margins.

Introduce two new text fields for bmin and bmax. Introduce
and set corresponding variables in class Model.

**Comment by pnrobinson** [comment]
*Updated GUI
*Added field to model for max kmer alignability with model.setMaxMeanKmerAlignability and analogous getter
* Connected this variable to value in GUI
* Set default value to 10 (int)
* I left the repeat score in the code in case we want it later.

**Comment by pnrobinson** [comment]
changed default GC score to 35% (See class called Default.java)

**Comment by hansenp** [comment]
max kmer alignability needs to be Double

**Comment by hansenp** [comment]
The mean kmer alignability of a bait is calculated as the sum of the alignability scores for all kmers within the bait divided by the number of all kmers within the bait.

For instance, a bait of length 120 has 120-50=70 50-mers. Assume that 69 have a score of 1 and one has a score of 2. Then the mean kmer alignability would be (69+2)/70=1,014285714.

**Comment by pnrobinson** [comment]
Yes, but for the setting, wouldn't it be simpler for users to restrict the minimum/maximum value to integers?

**Comment by hansenp** [comment]
Yes, maybe this would be easier. On the other hand, it would be more restrictive and maybe even misleading. The user should know what mean kmer alignability is.

**Comment by hansenp** [comment]
Cannot access parameters for initialization of fragments in 'model' because 'model' is null.

<img width="1126" alt="screen shot 2018-06-29 at 5 35 04 am" src="https://user-images.githubusercontent.com/10495485/42085452-71ceaba0-7b5e-11e8-875b-b55cd074c7e9.png">

**Comment by pnrobinson** [comment]
Put "design parameters" into main window
Delete b_min

Margin size needs to be in main GUI

Tiling factor can be deleted

**Comment by hansenp** [comment]
> Delete b_min

`b_max` should be deleted, not `b_min`

Furthermore, it would be nice if there were two checkboxes in the main window:

1. _Allow single margin_ (Maybe we rename this to _Allow unbalanced probes in margins_)
2. _Patch not centered or too short fragments_ (only for simple)

The second item refers to a new feature for simple viewpoint creation. If the segment containing the TSS does not cover more than 60% of the bases around the TSS because it is short or not well centered, Gopher tries to add an adjacent fragment. I hard coded the threshold 60%. Maybe there should be an additional text field for this. We could use the field that was previously used for `b_max`.

**Comment by hansenp** [comment]
Some suggestions for the setup tab:

![image](https://user-images.githubusercontent.com/10495485/42834078-507fe0b2-89f6-11e8-95f1-ca552191bf34.png)

**Comment by hansenp** [comment]
![image](https://user-images.githubusercontent.com/10495485/42874050-70f1d154-8a80-11e8-9447-be07af909c54.png)

**Comment by pnrobinson** [comment]
added bait size and margin size windows.
Still to do -- checkboxes.

**Comment by hansenp** [comment]
I thought about the layout of the setup tab. This is my suggestion for the **simple** approach:

![image](https://user-images.githubusercontent.com/10495485/42935006-db1cf7fc-8b48-11e8-9ae0-c04dcb4ffafc.png)

And this is my suggestion for the **extended** approach:

![image](https://user-images.githubusercontent.com/10495485/42935046-f91d0f94-8b48-11e8-9241-f2ed78723a79.png)

Furthermore, remove _Design parameters_ from menu bar.

**Comment by pnrobinson** [comment]
@hansenp   please check the update.
Also, should we just rename ``model.getAllowSingleMargin()`` (etc) to ``allowUnbalancedMargin``

Also, there is currently no place in Model for allow patched viewpoints -- should we make a new variable or where should this go?

**Comment by hansenp** [comment]
> should we make a new variable or where should this go

Yes, this would be great.

**Comment by pnrobinson** [comment]
@hansenp  I have refactored the GUI to a point where it is decent. 
There are still a few things to do, but since this Issue is so full, I will close it and make new issues for specific items. :-0
