### ISSUE TITLE
Analysis tab

### ISSUE THREAD

**Issue by pnrobinson** [TheJacksonLaboratory/Gopher#161]
Analysis tab
=======

Summary statistics:

  Total numbers of
 - [x] usable baits in unique selected fragments
 - [x] unique selected fragments
 - [x]   unique selected targetable fragments
 - [x] unique selected rescued fragments
 - [x]  resolved viewpoints
 - [x]  accesible genes

  Average numbers of
 - [x] nucleotides in selected fragments per viewpoint
 - [x] viewpoint score

  Remove
 - [x] Total margin size
 - [x]  Tiling factor
 - [x] Estimated number of probes

**Comment by pnrobinson** [comment]
Add checkbox etc if user has modified/checked a viewpoint
Show number of probes up/down

**Comment by pnrobinson** [comment]
@hansenp what is an accessible gene?

**Comment by pnrobinson** [comment]
I altered some of the code in ViewPointAnalysisSummaryHTMLGenerator for the new items -- could you check on the "Panel design" part of the Analysis tab if these are the items we want to have? Also, we need one additional item to balance the table (lower right cell) -- any suggestions?
I will now add a field for showing whether the viewpoint has been manually inspected

**Comment by hansenp** [comment]
An accessible is a gene with at least one viewpoint.

**Comment by hansenp** [comment]
> bp/viewpoint: 42.0 nucleotides

What is the difference between this and

> Average viewpoint size: 913.4 nucleotides

?

**Comment by hansenp** [comment]
> Also, we need one additional item to balance the table (lower right cell) -- any suggestions?

For a large number of genes it would be an interesting information how many genes were targeted and how many gene could be resolved (are accessible, i.e. have at least one viewpoint).

**Comment by pnrobinson** [comment]
I have not yet connected the view to the actualy values, 42.0 is just a place holder...

**Comment by hansenp** [comment]
Really! I was thinking the mice were playing a trick on us.

**Comment by hansenp** [comment]
Some suggestions for the layout:

![image](https://user-images.githubusercontent.com/10495485/42936996-0ac8f460-8b4e-11e8-9736-0d9d37c53b04.png)

**Comment by pnrobinson** [comment]
@hansenp  I have revised this so that it only shows the relevant values.
I do not know exactly how to calculate the number of rescued probes (I do see rescu-able but how do I know if they were actually rescued?)
@ielis Is there some way of getting rid of the whitespace underneath the table?

**Comment by hansenp** [comment]
Rescuable is redundant. Actually, there are three disjoint subsets of segments:

1. Unselectable: Not enoughf usable baits
2. Balanced: bmin baits can be placed in each margin
3. Unbalanced: 2 times bmin baits can be placed in both margins

I revised the decision tree to make things more clear.

![image](https://user-images.githubusercontent.com/10495485/43067044-83cbdf88-8e66-11e8-85e1-b1368fc5466d.png)

**Comment by pnrobinson** [comment]
Font size adjust
A little text

**Comment by pnrobinson** [comment]
revised and tested.
