### ISSUE TITLE
Viewpoint tab

### ISSUE THREAD

**Issue by pnrobinson** [TheJacksonLaboratory/Gopher#162]
Viewpoint tab
========

Repeat content:
Replace with average kmer alignabilty of baits.

Average kmer alignability and GC content:
Combine columns for upsteam and downstream
into one column (up/down).

Numbers of baits:
Show numbers of baits for upstream and downstream
margin.

Fragments neither targetable nor rescuable:
Make unselectable.

**Comment by hansenp** [comment]
@pnrobinson: I implemented corresponding function in class Segment:

```
public Double getMeanGCcontentOfBaits()
public Double getMeanAlignabilityOfBaits()
public Double getMeanRepeatContentOfBaits() // optional
```

**Comment by pnrobinson** [comment]
@hansenp please check -- I added mean kmer alignability and combined the repeatcontent to one column. I would continue to combine GC content and to add number of baits (up/down)

**Comment by hansenp** [comment]
Seems not to work yet.

<img width="1440" alt="screen shot 2018-07-15 at 9 38 06 am" src="https://user-images.githubusercontent.com/10495485/42734500-f32cd382-8812-11e8-9451-1569e67e26d1.png">

Will check this tomorrow.

**Comment by pnrobinson** [comment]
are you in the branch viewpointTab ?

**Comment by hansenp** [comment]
I'm in develop. I thought there was no separate branch viewpointTab

<img width="390" alt="screen shot 2018-07-15 at 9 54 48 am" src="https://user-images.githubusercontent.com/10495485/42734625-3b3e9e4c-8815-11e8-9160-15e76b02a69b.png">

**Comment by hansenp** [comment]
Now I can see it! Looks good. Maybe we could format the combined values for repeat like this

01.00%/01.00%

The the overall impression would be more tidy. Or we center the values of this column. Is this possible?

**Comment by hansenp** [comment]
The layout of the viewpoint tab looks strange on my computer:

<img width="719" alt="screen shot 2018-07-22 at 7 46 37 am" src="https://user-images.githubusercontent.com/10495485/43045268-81ea1d4e-8d83-11e8-964a-344d4fc5f2b9.png">

**Comment by hansenp** [comment]
Restriction enzymes should be in the section for design parameters.

**Comment by pnrobinson** [comment]
I will move the reastriction enzymes to design params. We will then need to work on the CSS to get things to look good!

**Comment by pnrobinson** [comment]
I have refactored this tab as above. There is an additional problem, but I will close this and start a new issue.
