### ISSUE TITLE
Reducing memory footprint of Alignability map

### ISSUE THREAD

**Issue by pnrobinson** [TheJacksonLaboratory/Gopher#167]
Currently, the following code is exectued in the method ``createViewPoints()`` in the class ``GopherMainPresenter``.
```
AlignabilityMap alignabilityMap = new AlignabilityMap(model.getChromInfoPathIncludingFileNameGz(),model.getAlignabilityMapPathIncludingFileNameGz(),50);
```
This will have the effect of keeping alignability information about the entire genome in this variable
```
 private HashMap<String,ArrayPair> alignabilityMap = null;
```
We could reimplement this so that we calculate the alignability map on a per chromosome basis.  One difficulty is that we do not have an index file for the BedGraph file. It might be useful to basically store a file handle in the class BedGraph that would remain at the last position of a chromosome until we need the next chromosome. And then to return one ``ArrayPair`` object at a time rather than storing these objects for all chromosomes in the map.

**Comment by hansenp** [comment]
Sounds difficult. What about breaking down the BedGraph file into files for individual chromosomes? Might this be easier to implement?

Another thing I do not understand is that the memory consumption increases to 8GB when the map is loaded even though in theory it should be 1GB.

**Comment by pnrobinson** [comment]
The creation of alignability maps and viewpoints is working. We have a sawtooth pattern during creation of viewpoints that presumably relates to reading in the chromosomes and the alignability map. Still, we have about 8Gb of used memory on the heap at the end of the process. VisualVM reports this as byte[]. 
I will look into better ways of finding out exactly what this 8 Gb of memory is -- maybe there is some active reference to a fastaReader or whatever that we do not want to store forever.
But it does seem to be better and more responsive than before the iterator.

**Comment by pnrobinson** [comment]
Using JProfiler on my laptop, there is less memory usage -- max 3 GB, down to about 1GB after a run with 32 genes/simple is completed. It seems that the sequences from HTSJDK are not being stored in memory and so I think that if a system has lots of memory, the JVM will use it and not necessarily trigger the garbage collector, but on smaller machines it appears to be OK. Therefore, I think we are now reasonably OK. I will close this issue
