### ISSUE TITLE
zoom behaviour

### ISSUE THREAD

**Issue by pnrobinson** [TheJacksonLaboratory/Gopher#171]
We need to have a separate update function for zooming with simple and extended to avoid choosing new segments if the user zooms with the simple approach.

**Comment by pnrobinson** [comment]
I meant that if you zoom out then there should be new segments that can be chosen--I do not think the list of segments is affected now by zooming. Do we want this?

**Comment by hansenp** [comment]
For the simple approach there can be at most 3 segments (selected or not). This is due to the implementation in function `generateViewpointSimple` in class `ViewPoint`:
```
                restrictionSegmentList.clear();
                if(upstreamSegment != null) {restrictionSegmentList.add(upstreamSegment);}
                if(centerSegment != null) {restrictionSegmentList.add(centerSegment);}
                if(downstreamSegment != null) {restrictionSegmentList.add(downstreamSegment);}
```

**Comment by hansenp** [comment]
I tested zooming works for the simple and extended approach. Selection of segments is not affected by zooming. I will close this issue.
