### ISSUE TITLE
Change position of Delete button in alalysis tab

### ISSUE THREAD

**Issue by hansenp** [TheJacksonLaboratory/Gopher#176]
When testing Gopher I often click accidentally the _Delete_ button even though I intend to click on the _Show_ button. It would be more failsafe if the _Delete_ button (and maybe soon the _Reset_ button) would be on the rigth side of the table.

**Comment by hansenp** [comment]
![image](https://user-images.githubusercontent.com/10495485/42632854-dd313888-85de-11e8-857c-e781795b9e68.png)

**Comment by pnrobinson** [comment]
done
