### ISSUE TITLE
Update readthedocs

### ISSUE THREAD

**Issue by hansenp** [TheJacksonLaboratory/Gopher#181]
Many changes were made. We should update the _readthedocs_. I would suggest to this after the main ideas were written down in the manuscript. We should take care that manuscript and documentation is consistent.

**Comment by hansenp** [comment]
I suggest to revise the structure of the documentation as follows:

```
* Short introduction of capture Hi-C

* Installation

* Basic concepts and terminology
    * Usable baits
    * Balanced and unbalanced margins

* Approaches
    + Simple and simple patched
    + Extended

* Graphical user interface
    + Design setup
        - Simple (patched)
        - Extended
    + Design overview
    + Viewpoint editing
    + Export of results
    + Collaborative work on projects
```

**Comment by pnrobinson** [comment]
agree!

**Comment by pnrobinson** [comment]
I merged everything into develop and then master to generate a new version of RTD online. I think we know we are working on this actively, so I will close this issue and if there is any specific problem that needs to be taken care of let's make specific issues!
