### ISSUE TITLE
Allow user to select all protein coding genes

### ISSUE THREAD

**Issue by pnrobinson** [TheJacksonLaboratory/Gopher#186]

**Comment by pnrobinson** [comment]
This feature is now committed to develop. It is relatively slow but it appears that Gopher can deal with all of the fragments. We can speed this up now by making the for loop parallel again and also reducing the amount of logging that is being produced. This function should now enable to user to create a Promoterome panel using the simple approach.
@hansenp  please check if this works on your end!

I will leave this open until the for loop has been parallelized and until we have check this a little more carefully. It is easy to extract all protein coding genes from UCSC.
One thing we could do in the RefSeq parser is to reduce the redundancy also -- right now the way that ValidGenes (ArrayList) is used is redundant.

**Comment by hansenp** [comment]
On my computer it finished without error within 2 hours for all protein coding genes.

**Comment by pnrobinson** [comment]
I have reduced the logging statements (which were excessive) and added in a parallelstream in place of the for loop and the calculations are noticably faster. Still checking....

**Comment by pnrobinson** [comment]
This is now working.
Generation of viewpoints (simple approach) took -2033.6 sec -- a little over a half an hour.
