### ISSUE TITLE
kmerSize

### ISSUE THREAD

**Issue by pnrobinson** [TheJacksonLaboratory/Gopher#189]
Do we need to allow the user to set the kmer size?
Currently, it is set in SimpleViewpoint CreationTask, e.g.,
  
int kmerSize=50; // TODO WHERE DOES THIS COME FROM?

Since we only have alignability files for 50nt, I suggest we do not allow this to be set by the user. But we
might want to put the consnt into the Default class

**Comment by hansenp** [comment]
For now we have only maps for 50mers, but we should definitely try 35mer at some point.

**Comment by pnrobinson** [comment]
OK -- for now, I would put DEFAULT.KmerSize=50 rather than have local variables ion each class.
