### ISSUE TITLE
simple/extended

### ISSUE THREAD

**Issue by pnrobinson** [TheJacksonLaboratory/Gopher#190]
Do we need a new name for simple and extended -- something like Panel and Global.
I do not think that anybody else will understand what "simple" and "extended" mean...

**Comment by hansenp** [comment]
I like simple and extended. Maybe we can explain it. Panel and Global could be misleading, because also Global is a panel. I thought about focused and broad, but this again misleading, because the lengths of the simple viewpoints depend on the enzyme. Will further think about this.

**Comment by pnrobinson** [comment]
I guess we will have to leave simple/extended unless we find better names, no big deal!
