### ISSUE TITLE
Setup tab: from OK to perfect

### ISSUE THREAD

**Issue by pnrobinson** [TheJacksonLaboratory/Gopher#192]
See this issue for history
https://github.com/TheJacksonLaboratory/Gopher/issues/160

- [x] Revise the panel that appears when the User clicks on Create New Viewpoints

**Comment by hansenp** [comment]
> Or something like that so that users know they need to click there to actually make the viewpoints?

Maybe something like this:

https://www.google.com/imgres?imgurl=https%3A%2F%2Fmedia2.giphy.com%2Fmedia%2FBo2WsocASVBm0%2Fgiphy.gif&imgrefurl=https%3A%2F%2Fgiphy.com%2Fexplore%2Fknight-rider&docid=SKEJRcwt-dt1EM&tbnid=NuvBpINwUdwk4M%3A&vet=10ahUKEwipp_zX7LTcAhXKY1AKHQbmClYQMwhHKAAwAA..i&w=480&h=360&bih=957&biw=1920&q=knight%20rider%20gif&ved=0ahUKEwipp_zX7LTcAhXKY1AKHQbmClYQMwhHKAAwAA&iact=mrc&uact=8

**Comment by pnrobinson** [comment]
I am going to close this issue -- I think the GUI is pretty slick and there are no specific problems now (also thanks to the recent patch). Please open a new issue if there are any specific problems with the setup tab.
