### ISSUE TITLE
Viewpoint tab: from OK to perfect

### ISSUE THREAD

**Issue by pnrobinson** [TheJacksonLaboratory/Gopher#193]
See here for history
https://github.com/TheJacksonLaboratory/Gopher/issues/162

**Comment by pnrobinson** [comment]
@hansenp please inspect this.
I am unlcear about when a Fragment should be unselectable. 
I have added the following code to ViewPointPresenter
```
 this.analysisPresenter.refreshVPTable();
            Segment segment = cdf.getValue().getSegment();
            CheckBox checkBox = cdf.getValue().getCheckBox();
            if (segment.isUnselectable()) {
                checkBox.setDisable(true);
            } else if (segment.isSelected()) {// inspect state of the segment and initialize CheckBox state accordingly
                checkBox.setSelected(true);
            }
```
is this correct? @ielis could you also take a look here please?

**Comment by hansenp** [comment]
A segment is _unselectable_, if it does not satisfy the specified design parameters with one exception. If the user sets _Allow unbalanced margins_ to _false_, then segments with unbalanced margins can be selected, if they satisfy all other constraints.

Whether a segment is _unselectable_, is determined on initialization of segments, and the the function `s.isUnselectable()` can be used to check this. Therefore, the code above seems to be correct.

**Comment by pnrobinson** [comment]
@hansenp  -- In this example, the middle fragment is selected (even though the GC is too high). It is a simple approach with a GWAS hit.
Also, there is one bait per fragment, but actually only the baits from the selected fragment would be exported, correct? Therefore, should we show the baits for non-selected fragments as "0/0"?

![gophergwas](https://user-images.githubusercontent.com/4943420/43110369-9151072a-8eb9-11e8-8477-3b50d4abd97f.png)

**Comment by hansenp** [comment]
> (even though the GC is too high)

I checked this. This is the GC content of the entire margins which does not mean that the margin cannot contain usable baits with 35% <= GC <= 65%. I would suggest to show the average GC content of selected baits (and the same for repeat content). The required functions `Double getMeanGCcontentOfBaitsUp()` etc. need to be implemented in the class `Segment`.

> Also, there is one bait per fragment, but actually only the baits from the selected fragment would be exported, correct? Therefore, should we show the baits for non-selected fragments as "0/0"?

There are two baits per digest, one in the upstream and one in the downstream margin. I would show the numbers of baits also for unselected digests. If the user selects additional digests it should be clear, if it is a balanced (1/1) or an unbalanced digest  (2/0, 0/2). The user should know that the baits of unselected digest will not be exported.

**Comment by hansenp** [comment]
The functions are already implemented in class Segment but never used.

```
    public Double getMeanGCcontentOfBaits() {
        Double meanGCcontentOfBaits = 0.0;
        for(Bait b : baitListUpStreamMargin) {
            meanGCcontentOfBaits = meanGCcontentOfBaits + b.getGCContent();
        }
        for(Bait b : baitListDownStreamMargin) {
            meanGCcontentOfBaits = meanGCcontentOfBaits + b.getGCContent();
        }
        return meanGCcontentOfBaits/this.getBaitNumTotal();
    }
```

Will try to connect this with the GUI.

**Comment by hansenp** [comment]
Now the columns in the table of viewpoint tab show only mean values derived from the baits.

![image](https://user-images.githubusercontent.com/10495485/43141398-14abc46a-8f56-11e8-8983-9e2c15f6d875.png)

@ielis: Could you please make the the values in columns _bp_, _Alignability_, _Repeat content_ and _Bait_ right-justified?

**Comment by pnrobinson** [comment]
I have right justified these columns
