### ISSUE TITLE
Add alarm window for unspecified enzyme

### ISSUE THREAD

**Issue by hansenp** [TheJacksonLaboratory/Gopher#196]
If I create viewpoints without specifying an enzyme, Gopher cannot complete the creation and the list of viewpoints remains empty. An alarm window should appear, if no enzyme is chosen.

**Comment by pnrobinson** [comment]
I had nearly the same error when I forgot to choose transcripts -- I think that there is a function for checking whether "everything is ready". We should attach this to the "GO" button

**Comment by pnrobinson** [comment]
Fixed this with https://github.com/TheJacksonLaboratory/Gopher/commit/1c233eb27ba6205eb624ef500a4ae11754efb955
