### ISSUE TITLE
Progress indicator reports “Done” while genome is still being decompressed

### ISSUE THREAD

**Issue by steinha** [TheJacksonLaboratory/Gopher#199]
The progress indicator assumes 25 blocks (chromosomes) when in reality there are 93 (hg19) or 455 (hg38).

https://github.com/TheJacksonLaboratory/Gopher/blob/1c233eb27ba6205eb624ef500a4ae11754efb955/src/main/java/gopher/io/GenomeGunZipper.java#L79-L80

https://github.com/TheJacksonLaboratory/Gopher/blob/1c233eb27ba6205eb624ef500a4ae11754efb955/src/main/java/gopher/io/GenomeGunZipper.java#L94-L95

**Comment by pnrobinson** [comment]
This was dealt with by the above commit.
