### ISSUE TITLE
Unintended localization breaks program

### ISSUE THREAD

**Issue by steinha** [TheJacksonLaboratory/Gopher#205]
When the default Locale of the user's JVM is not ``en-US``, Gopher may not work correctly. E.g., Gopher generates an exception when I click ``Show`` on any viewpoint:

![image](https://user-images.githubusercontent.com/5254933/43262272-d5acf028-90df-11e8-9d87-0f5e79af709c.png)

https://github.com/TheJacksonLaboratory/Gopher/blob/594a48542a69453389c66b7d05fceecf1b86880d/src/main/java/gopher/gui/viewpointpanel/ViewPointPresenter.java#L355-L357

``Double.parseDouble()`` only works with ``0.00%`` and does not work ``0,00%``.

Two possible solutions (I tested both):

1. In ``Gopher.main()``, add the following line: ``Locale.setDefault(new Locale("en", "US"));``
2. Change any ``String.format(`` to ``String.format(Locale.US, ``

**Comment by pnrobinson** [comment]
I would suggest let's go with option (1).

**Comment by pnrobinson** [comment]
I think this has been dealt with the Robin's patch
