### ISSUE TITLE
“Margin size” and “Bait size” fields are swapped in GUI

### ISSUE THREAD

**Issue by steinha** [TheJacksonLaboratory/Gopher#209]
![image](https://user-images.githubusercontent.com/5254933/43322921-6b2c1798-91b0-11e8-824d-2907baa8f365.png)

https://github.com/TheJacksonLaboratory/Gopher/blob/594a48542a69453389c66b7d05fceecf1b86880d/src/main/java/gopher/gui/gophermain/gophermain.fxml#L344-L363

**Comment by pnrobinson** [comment]
done
