### ISSUE TITLE
Suggestion/UX: Swap “New project” and “Open project” in welcome window

### ISSUE THREAD

**Issue by steinha** [TheJacksonLaboratory/Gopher#212]
If swapped, the order would follow the workflow.

![image](https://user-images.githubusercontent.com/5254933/43332077-8ee8785e-91c7-11e8-9196-56b604f49adc.png)

**Comment by pnrobinson** [comment]
but it might be confusing since the user might think they need to always start with a new project?

**Comment by steinha** [comment]
The two options could also be listed side-by-side.

**Comment by pnrobinson** [comment]
I have switched as suggested!
