### ISSUE TITLE
Gopher cannot derive viewpoints for GATA1 which was not the case for previous versions

### ISSUE THREAD

**Issue by hansenp** [TheJacksonLaboratory/Gopher#219]
If I create a new project and create viewpoints for GATA1 and DpnII without changing any other parameters

<img width="1106" alt="screen shot 2018-07-29 at 12 58 39 pm" src="https://user-images.githubusercontent.com/10495485/43368684-2b029b62-932f-11e8-9987-145bebdae76e.png">

<img width="582" alt="screen shot 2018-07-29 at 12 59 25 pm" src="https://user-images.githubusercontent.com/10495485/43368690-47d90f0a-932f-11e8-952d-d6f0e0e75a5c.png">

I get no viewpoint for GATA1 which was not the case for previous versions of Gopher.

<img width="1097" alt="screen shot 2018-07-29 at 1 02 41 pm" src="https://user-images.githubusercontent.com/10495485/43368724-d76fd360-932f-11e8-98aa-b665b46cf719.png">

Furthermore, the list of segments in the viewpoint tab has more than three segments:

<img width="1432" alt="screen shot 2018-07-29 at 1 04 41 pm" src="https://user-images.githubusercontent.com/10495485/43368744-214a0604-9330-11e8-83eb-c6798ec88b50.png">

**Comment by hansenp** [comment]
For the extended viewpoints, Gopher derives a viewpoint. But the segment containing the TSS is not selected

<img width="1413" alt="screen shot 2018-07-29 at 1 13 39 pm" src="https://user-images.githubusercontent.com/10495485/43368835-4440400a-9331-11e8-86d1-e91b1e5808aa.png">

btw this segment is unbalanced even though the option _Allow unbalanced margins_ is not selected (#218). This was also different in previous versions of Gopher.

**Comment by pnrobinson** [comment]
In UCSC, GATA1 has ``chrX:48644982-48652718 (+ strand)``.
The fragment that overlaps the TSS (which is at 48644982) is this one ``chrX:48643826-48644993 [len: 1168]`` Therefore, the overlap is 48644993-48644982+1=93-82+1=12 bp
Up to this point, everthing seems to be working correctly (following the log).

**Comment by pnrobinson** [comment]
If I select "allow unbalanced, everything works correctly (allowSingleMargin==true in this case).
Therefore, the problem is that there is no else here that will wind up showing three fragments (all unselected) for GATA1

**Comment by pnrobinson** [comment]
@hansenp  see line 575 in ViewPoint in the branch gata1-fix:
```
} else {
                // in this case, the center fragment was not selectable
                // if the user has not checked "allow unbalanced", then it might be desirable to allow the user to
                // select it manually. We need to show three fragments!
                Segment upstreamSegment = null;
                Segment downstreamSegment = null;
                int genomicPosFragIdx = restrictionSegmentList.indexOf(centerSegment);
                if (genomicPosFragIdx > 0) {
                    upstreamSegment = restrictionSegmentList.get(genomicPosFragIdx - 1);
                }
                if (genomicPosFragIdx < restrictionSegmentList.size() - 1) {
                    downstreamSegment = restrictionSegmentList.get(genomicPosFragIdx + 1);
                }
                restrictionSegmentList.clear();
                if(upstreamSegment != null) {restrictionSegmentList.add(upstreamSegment);}
                if(centerSegment != null) {restrictionSegmentList.add(centerSegment);}
                if(downstreamSegment != null) {restrictionSegmentList.add(downstreamSegment);}
            }
```
I think this fixes the problem. Please merge if OK!

**Comment by hansenp** [comment]
Ok, this works also for me. Only three segments for simple viewpoint without selected segments.

I mixed up GATA1 and TMEM167B (old figure for publication). I checked the upstream margin which has a GC content of  about 69%. Therefore, I can confirm that the center segment of GATA1 is correctly classified as unbalanced.
