### ISSUE TITLE
Alignability maps for HG38 & MM10

### ISSUE THREAD

**Issue by pnrobinson** [TheJacksonLaboratory/Gopher#230]
Figure out where to put these files and how to download automatically with GOPHER.

**Comment by steinha** [comment]
Related: I do not think it is ideal that alignability maps are downloaded from a random Dropbox link. Maybe there is a “more serious” domain like ``.jax.org`` or ``.charite.de`` available. Also, I think Dropbox has bandwidth limits (rumored to be 10 GB/day for free accounts and 250GB/day for paid accounts).

![image](https://user-images.githubusercontent.com/5254933/43446016-0633d84e-94a8-11e8-9421-741dffba9efc.png)

**Comment by hansenp** [comment]
I ask the Charite-IT. They set up a ticket and will contact me soon.

**Comment by hansenp** [comment]
We will also need to create maps for mm10 and hg38 using GEM library tools. A detailed description of how to do this can be found here:

https://wiki.bits.vib.be/index.php/Create_a_mappability_track#Install_and_run_the_GEM_library_tools

**Comment by hansenp** [comment]
I started the creation of maps for mm9, mm10, hg19 and hg38 on the JAX cluster. This will take about 60 hours to complete.

When the maps are finished, I will check if we get the same GOPHER results as before using the self-prepared map for hg19. 

We also have the ftp server but upload does not work yet.

**Comment by hansenp** [comment]
ftp upload works with:

`scp test_ftp.txt robinp@ftp.jax.org:~/ftp`

sftp works with:

`sftp robinp@ftp.jax.org`

entering of the ftp password and then:

```
sftp> cd ftp
sftp> ls
test_ftp.txt
```

**Comment by hansenp** [comment]
The creation of alignability maps for mm9, mm10, hg19 and hg38 completed. The sizes for the hg19 map from UCSC and the self-prepared map are slightly different.

UCSC:

`-rw-r--r--@ 1 hansep  JAX\Domain Users   **970M** Jun 21 04:32 wgEncodeCrgMapabilityAlign50mer.bedpraph.gz`

Self-prepared:

`-rw-rw-r-- 1 hansep jaxuser **955M** Aug 21 22:15 hg19_50.bedGraph.gz`

**Comment by hansenp** [comment]
ftp download works with wget as follows:

`wget ftp.jax.org:robinp/wgEncodeCrgMapabilityAlign50mer.bedpraph.gz`

**Comment by hansenp** [comment]
The hg19 map from UCSC contains canonical chromosomes only. Our pipeline for creation of the map produces maps contains all chromosomes. This is the reason for the 15 MB difference in size. Maybe this will cause GOPHER to become slow, because it iterates over all chromosomes in the map.

I will adjust the pipeline and remove non-canonical chromosomes from the map.

**Comment by hansenp** [comment]
After removal of non-canonical chromosomes, the self prepared map 16 MB is smaller than the map from UCSC.

`-rw-rw-r-- 1 hansep jaxuser **939M** Aug 22 06:38 hg19_50_2.bedGraph.gz`

Both maps contain entries for the identical set of chromosomes.

```
chr1
chr10
chr11
chr12
chr13
chr14
chr15
chr16
chr17
chr18
chr19
chr2
chr20
chr21
chr22
chr3
chr4
chr5
chr6
chr7
chr8
chr9
chrM
chrX
chrY
```

I will further compare the two maps. Maybe we have to remove the non-canonical chromosomes from FASTA before creating the map in order to get identical results.

**Comment by hansenp** [comment]
I uploaded self-prepared maps to our new FTP server and adjusted the download paths in the code. I tested the download for mm9, mm10, hg19 and hg38. This works.

I also created viewpoints for the example genes of human and mouse. This works for mm9, mm10 and hg19. However, for hg38 I receive the following error message:

![image](https://user-images.githubusercontent.com/10495485/44594412-68e4fa00-a7c6-11e8-9ad8-9511d170fd55.png)

I will further investigate this bug. It's not necessarily due to the map.

**Comment by hansenp** [comment]
Next, I checked whether the new maps affect the creation of viewpoints. For this purpose, I created viewpoints for our 730 CD4+ genes using the same parameter settings as for the GOPHER panel. (Allow single margins, bmin = 3 everything else on default). I get slightly different results.

This is summary for the viewpoints created with the old map from UCSC:
![image](https://user-images.githubusercontent.com/10495485/44594857-a007db00-a7c7-11e8-8b69-ab09801b1bd7.png)

And this is the summary for the viewpoints created with the new map:
![image](https://user-images.githubusercontent.com/10495485/44594901-bada4f80-a7c7-11e8-80d4-4e887bb43b31.png)

**Comment by hansenp** [comment]
The info to the track provided at UCSC states:
> These tracks provide a measure of how often the sequence found at the particular location will align within the whole genome. Unlike measures of uniqueness, alignability will tolerate up to 2 mismatches. These tracks are in the form of signals ranging from 0 to 1 and have several configuration options.

And the help of the GEM program lokks as follows:
```
Usage:
 gem-mappability
  -I <index_prefix>                       (mandatory)
  -C|--emulate-complement                 (for indices lacking it)
  --granularity <number>                  (default=10000)
  -o <output_prefix>                      (mandatory)
  --output-line-width <number>            (default=70)
  -l <read_length>                        (mandatory)
  -t|--approximation-threshold <number>|'disable'
                                          (default: first multiple bin)
  --mismatch-alphabet <symbols>           (default="ACGT")
  -m <max_mismatches>|<%_mismatches>      (default=0.04)
  -e <max_edit_distance>|<%_differences>  (default=0.04)
  --max-big-indel-length <number>         (default=15)
  --min-matched-bases <number>|<%>        (default=0.80)
  -s|--strata-after-best <number>         (default=1)
  -T <thread_number>                      (default=1)
  --show-license                          (print license)
  -h|--help                               (print usage)
```
I think the relevant options are `-m` and `-e`. But 50 (kmer size) * 0.04 is 2. I will try to recalculate the map with `-m 2` and `-e 2`. Then I will compare the maps again.

@pnrobinson: Any suggestions?

**Comment by hansenp** [comment]
This is the usage output of the indexer:
```
Usage:
 gem-indexer
  -i <input_file>                 (mandatory)
  -o <index_output_prefix>        (mandatory)
  -c|--content-type 'dna'|'protein'
                                  (default='dna')
  --force-fm-general-index        (default: deduced from content)
  --filter-function 'iupac-dna'|'iupac-colorspace-dna'|'none'
                                  (default='iupac-dna' for DNA,
                                           'none' for protein)
  --colorspace                    (same as
                                   '--filter-function iupac-colorspace-dna')
  --strip-unknown-bases-threshold 'disable'|<integer>
                                  (default=50 for DNA,
                                           'disable' for protein)
  --complement-size-threshold <integer>
                                  (default=2GB)
  --complement 'yes'|'emulate'|'no'
                                  (default='yes' for DNA below threshold,
                                           'emulate' for DNA above threshold,
                                           'no' for protein)
  -T|--threads <thread_number>    (for the BWT generator,
                                   default=1)
  -m|--max-memory 'force-slow-algorithm'|'unlimited'|<integer>
                                  (generate the BWT with a slower algorithm
                                    if more RAM is required,
                                   default=2GB)
  -s|--sampling-rate <integer>    (default=32 -- 16/32/64/128 ok)
  --max-split-length <integer>    (default=1000000)
  --max-read-length <integer>     (default=1000)
  --keep-temporaries              (default: deleted in the end)
  --mm-tmp-prefix <prefix>        (default="/tmp/mm_new-")
  --check-index                   (default=false)
  --verbose                       (default=false)
  --show-license                  (print license and exit)
  -h|--help                       (print usage and exit)
```

**Comment by hansenp** [comment]
The self-prepared map seems to be more sensitive.

**Comment by pnrobinson** [comment]
Note that we need to add a section to the methods about how we generate these maps! @hansenp

**Comment by hansenp** [comment]
It seems to make a difference whether I'm using the default `-m 0.04` or -`m 2`. The file sizes are different:

```
[hansep@helix gem_ali_maps]$ ls -l hg38_old/hg38_50.bedGraph.gz 
-rw-rw-r-- 1 hansep jaxuser 1047599003 Aug 23 05:53 hg38_old/hg38_50.bedGraph.gz
[hansep@helix gem_ali_maps]$ ls -l hg38/hg38_50.canonical.bedGraph.gz 
-rw-rw-r-- 1 hansep jaxuser 1049093939 Aug 26 06:35 hg38/hg38_50.canonical.bedGraph.gz
```

The first file corresponds to `-m 0.04` and the second file to `m 2`. I will further investigate this.

**Comment by hansenp** [comment]
This is a comparison of the alignability UCSC map (top) and the self-prepared maps for default parameters (middle) and with the `-m 2` option (bottom).

For the entire genome:
<img width="1422" alt="screen shot 2018-08-28 at 5 32 58 am" src="https://user-images.githubusercontent.com/10495485/44714663-e1c4aa00-aa83-11e8-81ad-903ced1129e5.png">

For chromosome 21:
<img width="1420" alt="screen shot 2018-08-28 at 5 34 40 am" src="https://user-images.githubusercontent.com/10495485/44714762-1cc6dd80-aa84-11e8-9b2a-255c5f8fea6b.png">

Zoomed in to 1000 kbp:
<img width="1421" alt="screen shot 2018-08-28 at 5 37 17 am" src="https://user-images.githubusercontent.com/10495485/44714904-762f0c80-aa84-11e8-9009-91868e310762.png">

Zoomed in to 100 kbp:
<img width="1421" alt="screen shot 2018-08-28 at 5 40 27 am" src="https://user-images.githubusercontent.com/10495485/44715094-f2c1eb00-aa84-11e8-847f-a46945a9493c.png">

Zoomed in to 10 kbp:
<img width="1418" alt="screen shot 2018-08-28 at 5 42 08 am" src="https://user-images.githubusercontent.com/10495485/44715232-3a487700-aa85-11e8-83d4-61d1fd8334d6.png">

Zoomed in to 1 kbp:
<img width="1422" alt="screen shot 2018-08-28 at 5 44 25 am" src="https://user-images.githubusercontent.com/10495485/44715332-87c4e400-aa85-11e8-8cf3-63b9e4d7d8d6.png">

Zoomed in to 100 bp:
<img width="1421" alt="screen shot 2018-08-28 at 5 46 32 am" src="https://user-images.githubusercontent.com/10495485/44715442-ceb2d980-aa85-11e8-9c49-1658b50b0f14.png">

**Comment by hansenp** [comment]
I also built the index only on canonical chromosomes. But there are only minor differences as compared to the maps built with indices of all chromosomes, and the created maps are still different from the original map (UCSC). I also visualized the tracks in IGV (last two tracks).

Zoomed in to 100 bp:
<img width="1423" alt="screen shot 2018-08-29 at 5 02 09 am" src="https://user-images.githubusercontent.com/10495485/44777771-6f1e0200-ab49-11e8-9d7f-60858ff98d93.png">

Zoomed in to 1 kbp:
<img width="1422" alt="screen shot 2018-08-29 at 5 09 30 am" src="https://user-images.githubusercontent.com/10495485/44777937-cc19b800-ab49-11e8-8a13-c73d10987e80.png">

Zoomed in to 10 kbp:
<img width="1422" alt="screen shot 2018-08-29 at 5 10 55 am" src="https://user-images.githubusercontent.com/10495485/44778038-084d1880-ab4a-11e8-845c-389838e06aad.png">

**Comment by pnrobinson** [comment]
One other possibility would be to ask on the UCSC mailing list--in the past they have been extremely helpful for questions I had. But perhaps it is OK to just use the UCSC tracks for hg19/mm9 and our own tracks for hg38/mm10, and we can figure out the subtle differences for the revision.

**Comment by hansenp** [comment]
Yes, for now we are using the UCSC maps for  hg19/mm9 and the self-prepared for hg38/mm10. I think this is ok.

But I have also sent an email to Thomas Derrien and Paolo Ribeca, the developers of GEMTools and creators of the original maps.
