### ISSUE TITLE
Only 24 extended viewpoints for 500 genes

### ISSUE THREAD

**Issue by hansenp** [TheJacksonLaboratory/Gopher#231]
If I run the simple or simple patched approach with set to false on 500 randomly selected genes, I get about 450 valid viewpoint but only 24 for the extended approach.

![image](https://user-images.githubusercontent.com/10495485/43401277-010e5274-9410-11e8-9653-3b42e2ee23d4.png)

**Comment by hansenp** [comment]
@pnrobinson: What is digests/viewpoints?

**Comment by pnrobinson** [comment]
When I create simple and extended viewpoints for the 32 human genes in the test file, I get
29/32 -- simple 
32/32 -- extended
i.e., it seems to be working. Can you share these 500 random genes?

digests/viewpoint is the average number of digests per viewpoint -- I guess this is not very clear?

**Comment by hansenp** [comment]
Sorry, forgot to check out the latest version.
