### ISSUE TITLE
Analysis tab

### ISSUE THREAD

**Issue by hansenp** [TheJacksonLaboratory/Gopher#232]
![image](https://user-images.githubusercontent.com/10495485/43406349-5167f188-941c-11e8-88fc-661cf519c954.png)

Suggestions:

1. Add 1 after greater or equal signs.
2. Total unique digests and active digests seem to be redundant.
3. Balanced and unbalanced digests belong to digests, not to probes.
4. Instead of putting everything in one line we could do it like this:

```
Gene                 gene_val_1
                     gene_val_2
Viewpoints           vp_val_1
                     vp_val_2
                     vp_val_3
```

**Comment by hansenp** [comment]
If I create simple viewpoint for 499 valid gene symbols the analysis tab reports 499 genes. But if I do the same with the simple patched or extended approach, the analysis tab reports only 498 genes, even though I uploaded the same text file with gene symbols. I'm on the latest version of the develop branch and checked this twice.

**Comment by hansenp** [comment]
We could add the number of patched viewpoints.

**Comment by pnrobinson** [comment]
I fixed everything. I got 10 patched viewpoints for a panel with 580 viewpoints.
```
 int nviewpoints = design.getN_viewpoints();
        int resolvedVP = design.getN_resolvedViewpoints();
        double avVpSize = design.getAvgVPsize();
        double avgVpScore = design.getAvgVPscore();
        String vpointV = String.format("n=%d of which %d have \u2265 1 valid fragment.",
                nviewpoints,resolvedVP);
        if (model.getApproach().equals(Model.Approach.SIMPLE)) {
            int n_patched=design.getN_patched_viewpoints();
            vpointV=String.format("%s %d viewpoints were patched",vpointV,n_patched);
        }
        listItems.put("Viewpoints",vpointV);
```
@hansenp  please check the way I ddid this in the Design class (relevant code above). If all is well, please close the issue.

**Comment by hansenp** [comment]
I further revised the output. I pushed this to develop. I now looks like this:

![image](https://user-images.githubusercontent.com/10495485/43447357-a0b6fa24-94ab-11e8-8887-83786acb244b.png)

I minor detail: If I maximize the window the summary table does not expand.

@pnrobinson: Is this easy to fix?

**Comment by pnrobinson** [comment]
The fix for this was to add a fxml id (listviewHbox) to the HBox that holds both of the ListView's and to add this to the presenter class
```
  listviewHbox.setHgrow(lviewValue, Priority.ALWAYS);
```
