### ISSUE TITLE
Trying to validate an empty gene list generates an exception

### ISSUE THREAD

**Issue by steinha** [TheJacksonLaboratory/Gopher#234]
![0](https://user-images.githubusercontent.com/5254933/43410519-6e6bee14-9427-11e8-9ecf-ce753daa299b.png)

![image](https://user-images.githubusercontent.com/5254933/43410348-e67dfd80-9426-11e8-90bc-27c4fb59bc73.png)

**Comment by pnrobinson** [comment]
If there are no gene symbols or if the symbols are invalid, then an empty list is returned or an error dialog appears. The user cannot go on to make viewpoints because at least one valid gene symbol is required.

**Comment by steinha** [comment]
@pnrobinson, Are you saying the ``RuntimeException`` thrown by ``FXMLLoader.java`` is intended? As far as I can tell, the exception is caught from below when ``invalidGeneSymbols`` is ``null``:

https://github.com/TheJacksonLaboratory/Gopher/blob/54a8f0afec2b67337964a0dcc192098cdb9cf32f/src/main/java/gopher/io/RefGeneParser.java#L149-L154

**Comment by pnrobinson** [comment]
I think I have fixed this--I can no longer replicate the exception. Reopen please if problem persists.
