### ISSUE TITLE
Button labels in gene list sometimes jump around

### ISSUE THREAD

**Issue by steinha** [TheJacksonLaboratory/Gopher#235]
Labels ``Upload``, ``Clipboard`` and ``Accept`` sometimes jump on *mouseover* or *mousedown*. See below. I cannot reproduce this behavior consistently.

![mouseover](https://user-images.githubusercontent.com/5254933/43410840-93ba890e-9428-11e8-99b1-c3ee34e2cfcf.gif)

![mouseover](https://user-images.githubusercontent.com/5254933/43411811-954da0a0-942b-11e8-995b-cd60d584c21b.gif)

**Comment by pnrobinson** [comment]
The jumping behavior is coming from the CSS -- if this is annoying we can turn it off!

**Comment by steinha** [comment]
The behavior should be consistent across button labels in my opinion. ``Upload``, ``Clipboard`` and ``Accept`` sometimes jump, ``Validate`` and ``Cancle`` remain in place. In the main GUI, button labels generally remain in place.

**Comment by pnrobinson** [comment]
Difficult -- they all have the same CSS, and on my system it all works great (linux). Are you trying this in Windows? @steinha 
Tomorrow I will try on my mac.

**Comment by steinha** [comment]
This isn't a CSS issue. The three buttons are missing the ``alignment="CENTER"`` attribute in ``entrezgene.fxml``, which the other two buttons have. Pull request #240 is a fix.

E.g., 
https://github.com/TheJacksonLaboratory/Gopher/blob/6d3e8e6c1f2a15b33d8073bd2b72cbd265f783b8/src/main/java/gopher/gui/entrezgenetable/entrezgene.fxml#L20

https://github.com/TheJacksonLaboratory/Gopher/blob/6d3e8e6c1f2a15b33d8073bd2b72cbd265f783b8/src/main/java/gopher/gui/entrezgenetable/entrezgene.fxml#L38-L39

**Comment by pnrobinson** [comment]
I was able to reproduce this issue right now and figured out that for some reason, the alignment="CENTER" was causing it (only two of the buttons had this attribute). Once I removed this, the problem no longer occured.

**Comment by pnrobinson** [comment]
Sorry, I am doing this out of order. I guess we found the same bug fix. Please reopen if necessary, thanks!
