### ISSUE TITLE
Report contains “TODO NEW !!!!!” lines

### ISSUE THREAD

**Issue by steinha** [TheJacksonLaboratory/Gopher#237]
``Export > Display report``

![image](https://user-images.githubusercontent.com/5254933/43412454-96c84d66-942d-11e8-9e5a-7b22e49e7d71.png)

**Comment by pnrobinson** [comment]
@hansenp Can we discuss the format and contents of this file tomorrow. It should be easy to implement now that most everything else is working...

**Comment by hansenp** [comment]
Yes, let's discuss this via skype.

**Comment by pnrobinson** [comment]
I will basically add all of the information from all of the fields we have -- I will try to implement this today in the evening.

**Comment by pnrobinson** [comment]
Fixed, and improved the look and feel a little.
