### ISSUE TITLE
Improve gene list UX

### ISSUE THREAD

**Issue by steinha** [TheJacksonLaboratory/Gopher#239]
A couple of suggestions to improve the UX for new users of supplying a gene list.

1. The GUI says ``Enter gene list`` and ``Enter genes`` everywhere. Would not “Supply gene list” fit better? “Enter” may lead users to believe that they can type in a text field.

   ![image](https://user-images.githubusercontent.com/5254933/43449851-c0ca2ef2-94b1-11e8-96db-138da035bb1a.png)

2. Replace the highlighted texts with something like “Alternatively, use the ``Clipboard`` button to load the gene symbols from text in the clipboard” and “proceeding. Finally, click on ``Accept``”.

   ![image](https://user-images.githubusercontent.com/5254933/43450199-7a135bae-94b2-11e8-968e-ad009ac11913.png)

3. Consider adding numbers before buttons like below. Also, make buttons the same size.

   ![image](https://user-images.githubusercontent.com/5254933/43450527-30f1e138-94b3-11e8-8e8f-a2494552afb4.png)

4. ``Help > Example gene sets`` are a great feature for new users. If it is easy, change the title to something like “Example Gene List” and hide the ``Upload`` and ``Clipboard`` buttons (https://github.com/TheJacksonLaboratory/Gopher/issues/233#issuecomment-408925033).

   ![image](https://user-images.githubusercontent.com/5254933/43450750-b7a16eec-94b3-11e8-9763-332ed8ba8261.png)

**Comment by pnrobinson** [comment]
@steinha  I managed to fix all of these problems except Help > Example gene sets. I think that we can just mention in the tutorial what the user needs to do, and it might even be better to remove this feature, since it was mainly intended to help speed development, and we can assume that any user of this program will have easy access to gene lists.
