### ISSUE TITLE
Provide visual feedback after loading target gene list

### ISSUE THREAD

**Issue by steinha** [TheJacksonLaboratory/Gopher#242]
The GUI shows nice blue check marks indicating that data sources have been downloaded. The GUI also indicates in blue which restriction enzyme has been selected. 

It does not show any indication about loaded target gene symbols. If it is easy, why not add a blue label below the ``target gene list`` button that reads “not initialized” or “### gene symbols selected”.

![image](https://user-images.githubusercontent.com/5254933/43476630-5b3ea9f8-94f9-11e8-8115-96e45c936980.png)

**Comment by pnrobinson** [comment]
+1, I will try this

**Comment by pnrobinson** [comment]
I have added feedback. This will only work after you have loaded genes or BED targets. After you save, Gopher will remember it. It seemed better not to put not initialized under all three since you only need to initialize one of them.
