### ISSUE TITLE
Update version string before release

### ISSUE THREAD

**Issue by steinha** [TheJacksonLaboratory/Gopher#246]
``Help > About``

![image](https://user-images.githubusercontent.com/5254933/43523530-f5833c9c-959c-11e8-94c5-c7223d7d9e43.png)

Change it here:

https://github.com/TheJacksonLaboratory/Gopher/blob/e48acfdd5a23bee40ed9d044db4307d380556a39/src/main/java/gopher/model/Model.java#L27-L30

**Comment by pnrobinson** [comment]
I have update this. Please note that if you build from IntelliJ, the versions in the Strings are used. If you build with maven, I have added a function to get the latest version from the POM file
```
  /** @return the version number. */
    public static String getVersion() {
        String version = "0.0.0";// default, should be overwritten by the following.
        try {
            Package p = Model.class.getPackage();
            version = p.getImplementationVersion();
        } catch (Exception e) {
            // do nothing
        }
        return VERSION;
    }
```
and in the POM
```
<archive>
  <manifest>
         <mainClass>gopher.Gopher</mainClass>
          <addDefaultImplementationEntries>true</addDefaultImplementationEntries>
          <addDefaultSpecificationEntries>true</addDefaultSpecificationEntries>
     </manifest>
</archive>
```
