### ISSUE TITLE
Add feedback when user is offline

### ISSUE THREAD

**Issue by steinha** [TheJacksonLaboratory/Gopher#247]
There are many reasons why an Internet connection may not work (e.g., firewall, proxy, server problems). If it is easy, add an error message and mention the ``Edit > Add proxy`` setting.

*What happens now when the user is offline?*

1. When attempting to download data sources: Error message and exception.

   ![image](https://user-images.githubusercontent.com/5254933/43522393-800ecd76-9599-11e8-8d7c-2a63423e2e85.png)

   ![image](https://user-images.githubusercontent.com/5254933/43522406-8e07273e-9599-11e8-9d53-a7a425e6b040.png)

2. When clicking ``Show`` on a viewpoint: Upper panel remains empty and no feedback.

   ![image](https://user-images.githubusercontent.com/5254933/43522682-5f5dee6c-959a-11e8-86c3-5f7e0df0160e.png)

3. Selecting a fragment: Spinning wheel.

   ![image](https://user-images.githubusercontent.com/5254933/43522764-9a26d9f0-959a-11e8-8424-d7698f74875c.png)

4. Open ReadTheDocs: Empty page.

   ![image](https://user-images.githubusercontent.com/5254933/43523749-ae9dd6ce-959d-11e8-9821-2fd534addedc.png)

**Comment by pnrobinson** [comment]
@steinha I am not sure how best to do this in Java and probably cannot do this today. I think we can check the http return code but I am not sure how to enforce that we do not wait forever if there is not internet connection.

**Comment by pnrobinson** [comment]
I have researched this but have not been able to find any way to do this using the JavaFX framework. Surprising because it seems like an obvious issue. We need to add a troubleshooting page to the online documentation -- but I hope it is fair to assume that most people will be online at most time anyway...

**Comment by pnrobinson** [comment]
I have added a troubleshooting page to the documentation about this issue.
