### ISSUE TITLE
Once a viewpoint tab is closed, the same tab cannot be opened again

### ISSUE THREAD

**Issue by steinha** [TheJacksonLaboratory/Gopher#248]
![double](https://user-images.githubusercontent.com/5254933/43525022-fce6f704-95a0-11e8-9b81-11be8e92b53c.gif)

**Comment by pnrobinson** [comment]
This was happening because of an error in the bookkeeping of opentabs. I needed that change this and I also needed to capture the close event and make sure we do book keeping before closing the tab
```
tab.setOnCloseRequest((e)-> {
            for (ViewPoint vpnt : this.openTabs.keySet()) {
                Tab t = this.openTabs.get(vpnt);
                if (t.equals(tab)) {
                    this.openTabs.remove(vpnt);
                }
            }
        });
```
