### ISSUE TITLE
Default window width is too small for viewpoint tab

### ISSUE THREAD

**Issue by steinha** [TheJacksonLaboratory/Gopher#251]
Default window width:
![image](https://user-images.githubusercontent.com/5254933/43528009-45e475d8-95a8-11e8-8f95-0117e52f322a.png)

Full view requires manual resize:
![image](https://user-images.githubusercontent.com/5254933/43528043-565fe94c-95a8-11e8-9221-1a4f1f9e77d7.png)

**Comment by pnrobinson** [comment]
This is difficult right now. The width of the viewpoint panel is supposed to be 1165, but we need to check how wide the UCSC scene wants to be.

**Comment by pnrobinson** [comment]
Thanks, this is looking good now!
