### ISSUE TITLE
Score changes from 0.00% to 100.0% by opening viewpoint tab

### ISSUE THREAD

**Issue by steinha** [TheJacksonLaboratory/Gopher#252]
Viewpoints below were generated with simple approach.

![score1](https://user-images.githubusercontent.com/5254933/43529154-f07c7b74-95aa-11e8-97fe-db1048fbdb45.gif)

**Comment by pnrobinson** [comment]
The calculation of score is not taking into account whether the viewpoint has zero active digests. I fixed this and the GUI now works as expected.
