### ISSUE TITLE
Sixth line is hidden in panel design summary

### ISSUE THREAD

**Issue by steinha** [TheJacksonLaboratory/Gopher#254]
Only the first five lines are displayed and the upper panel cannot be resized.

![image](https://user-images.githubusercontent.com/5254933/43531443-105fa98e-95b0-11e8-9bd7-11c8b13b85f6.png)

**Comment by pnrobinson** [comment]
Apparently it is difficult to adjust the height of the ListView so that it exactly fits. I think it depends to some extent on the height of the font. Was this on windows? Probably the fonts are bigger. @ielis do you have an idea of what to do here?

**Comment by pnrobinson** [comment]
In linux and Mac the height is OK, I think.
