### ISSUE TITLE
Design statistics: Capture Size

### ISSUE THREAD

**Issue by hansenp** [TheJacksonLaboratory/Gopher#255]
Agilent's SureDesign-Wizard calculates the `Capture Size` for probes. This is the total region that is covered by all probes. We could add this to our table for Panel-Design.

A simple, quick and inefficient implementation could be to iterate over all (unique) probes and add each position to set. The final size of  corresponds to the  `Capture Size`. I think efficiency is not important here, because the number of all probe positions cannot become very large. We could use this and improve the implementation later if necessary.

@pnrobinson: What do you think?

**Comment by pnrobinson** [comment]
SInce all probes have the same size, can't we just multiple the number of probes times this size?

**Comment by hansenp** [comment]
No, because the probes overlap.

**Comment by hansenp** [comment]
I implemented this as described above. I checked this by comparing the capture sizes calculated by the SureDesign wizard and Gopher.

![image](https://user-images.githubusercontent.com/10495485/44346677-d62b1f00-a496-11e8-8550-eb868781a2ca.png)

 
![image](https://user-images.githubusercontent.com/10495485/44346695-e8a55880-a496-11e8-9c7c-3c1c0064e81a.png)

I will close this issue.
