### ISSUE TITLE
“Ctrl+N” does not clear blue genes text field and sets design parameters to 0

### ISSUE THREAD

**Issue by steinha** [TheJacksonLaboratory/Gopher#257]
Creating a new project does not clear blue target genes text field. Furthermore, when previous project was saved with non-default design parameters, these are set to 0 when selecting ``File > New (Ctrl+N)``:

![new1](https://user-images.githubusercontent.com/5254933/43592899-d644d32e-9676-11e8-8d93-b3473b8483cc.gif)

**Comment by pnrobinson** [comment]
@steinha I added some code to clear the target gene list.
I cannot reproduce the bug that hitting ctrl-N causes the minimum fragment size to go to zero...

**Comment by pnrobinson** [comment]
There is also an issue that the gene count is getting set to 1 when I enter the 32 example human genes.

**Comment by pnrobinson** [comment]
fixed the issue with the gene count.
