### ISSUE TITLE
Consider hiding or emptying unused design parameters in Simple and Extended approach

### ISSUE THREAD

**Issue by steinha** [TheJacksonLaboratory/Gopher#258]
When a deactivated form field has a value, the user could think that the value is relevant but can't be changed. E.g., below, the user could think that viewpoints need to be patched with the Extended approach.

![image](https://user-images.githubusercontent.com/5254933/43587792-525fa2e2-966b-11e8-85c4-ce4ca96b7145.png)

I would propose either hiding or emptying unused design parameters like so:

Hiding:
![image](https://user-images.githubusercontent.com/5254933/43587817-5d5fd216-966b-11e8-9f86-454a388be8a9.png)

Emptying:
![image](https://user-images.githubusercontent.com/5254933/43587824-6224040c-966b-11e8-8c89-a1c9c10ae26e.png)

**Comment by pnrobinson** [comment]
The GUI now removes the checkmark if the user goes from Simple to extended.  The textfields (but not the labels) are sewt to invisible for simple.
