### ISSUE TITLE
Revised viewpoints cannot be reset

### ISSUE THREAD

**Issue by hansenp** [TheJacksonLaboratory/Gopher#264]
![peek 2018-08-03 19-20](https://user-images.githubusercontent.com/10495485/43655983-19c2031c-9751-11e8-97e0-58fb467d3d4c.gif)

**Comment by pnrobinson** [comment]
I can revise viewpoints with no error -- please check again @hansenp

**Comment by hansenp** [comment]
No error for me as well. Will close this issue.
