### ISSUE TITLE
terminology

### ISSUE THREAD

**Issue by pnrobinson** [TheJacksonLaboratory/Gopher#270]
@hansenp 
We need to standardize
bait vs probe (suggestion -- use bait
digest vs fragment -- suggestion -- digest for restriction fragment. fragment for sonication fragment.
If we agree, then change min fragment length in setup tab to minimum digest length

**Comment by hansenp** [comment]
> bait vs probe (suggestion -- use bait

We should use _probe_ because of GO**P**HER

I will replace _fragment_ to _digest_ in setup tab.

**Comment by hansenp** [comment]
@pnrobinson Shall we also change _bait_ to _probe_?

**Comment by pnrobinson** [comment]
yes!

**Comment by hansenp** [comment]
I replaced all occurrences of _baits_ with _probes_. I will close this issue.
