### ISSUE TITLE
"n/a"

### ISSUE THREAD

**Issue by pnrobinson** [TheJacksonLaboratory/Gopher#273]
I think we should report "n/a" for digests that are too short to enrich. 
However, the GUI is reporting "n/a" for longer digests (e.g., 175 bp) and it is not possible to select them (extended approach).

**Comment by hansenp** [comment]
@pnrobinson: Can you give an example? Digests might also be unselectable because there were no probes that satisfy the constraints regarding GC content and alignability.

**Comment by pnrobinson** [comment]
write about this in text

**Comment by pnrobinson** [comment]
I have expanded the text to this:
```
In some cases, the surrounding digests cannot be chosen because they are too short 
or no baits can be found which satisfy the chosen GC or alignability constraints. In this 
case, GOPHER shows ``n/a'' in red. 
```
