### ISSUE TITLE
GOPHER icon and GH pages

### ISSUE THREAD

**Issue by hansenp** [TheJacksonLaboratory/Gopher#274]
I revised the GOPHER icon.

<img width="612" alt="screen shot 2018-08-22 at 4 31 02 am" src="https://user-images.githubusercontent.com/10495485/44452319-38357280-a5c4-11e8-97a0-0993cf49718d.png">

Maybe we should also create a GitHub page similar to this for Q:

http://charite.github.io/Q/

**Comment by pnrobinson** [comment]
The new icon looks great!
As just discussed, we would stick to the read the docs documentation instead of GitHub IO
