### ISSUE TITLE
Table with output files for manuscript

### ISSUE THREAD

**Issue by pnrobinson** [TheJacksonLaboratory/Gopher#275]

**Comment by hansenp** [comment]
I renamed output files as follows:

`_vpvSummary.tsv` to `_viewPoints.tsv`
`_unique_target_fragments.bed` to `_uniqueTargetDigests.bed`
`_targetRegions.txt` to `_uniqueTargetDigestMargins.txt`

I removed `_vpvSummary.r` from output, because it was unfinished.

**Comment by hansenp** [comment]
I changed the output of the digest file. Until now a directory had to be chosen, and a filename had to be specified. I adjusted this to the output of BED files. Now a directory has to be chosen, and no file name can be specified. The predefined file name has the following form:

`<PROJECT_NAME>_<GENOME_BUILD>_DigestedGenome.txt`

**Comment by hansenp** [comment]
I added a table for the output files to the manuscript. But I'm unhappy with the formatting. @pnrobinson: Do you have any suggestions?

**Comment by steinha** [comment]
If you do not want to break long filenames, how about merging the two other columns?
![image](https://user-images.githubusercontent.com/5254933/44547293-e94e2100-a71a-11e8-870c-fd669d6323d8.png)
(This was done with nested ``tabular`` environments.)

**Comment by hansenp** [comment]
@steinha: I followed your suggestion and now it looks good. Many thanks!

I finished the table for output files and will close this issue-
