### ISSUE TITLE
Released jar with dependencies cannot be excuted on mac

### ISSUE THREAD

**Issue by hansenp** [TheJacksonLaboratory/Gopher#276]
Uwes-MacBook-Pro:Gopher-master ukornak$ java -jar GopherGui-0.4.7-jar-with-dependencies.jar 
Exception in thread "main" java.lang.UnsupportedClassVersionError: gopher/Gopher : Unsupported major.minor version 52.0
at java.lang.ClassLoader.defineClass1(Native Method)
at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
at java.security.AccessController.doPrivileged(Native Method)
at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
at java.lang.ClassLoader.loadClass(ClassLoader.java:247)

**Comment by pnrobinson** [comment]
The error regarding the unsupported major.minor version is because during compile time you are using a higher JDK and a lower JDK during runtime.

Does Uwe's Mac have Java 1.8?

**Comment by pnrobinson** [comment]
If this is a Java version issue, then we should add this point to the troubleshooting document:
https://gopher.readthedocs.io/en/latest/08_troubleshooting.html

**Comment by hansenp** [comment]
https://stackoverflow.com/questions/22489398/unsupported-major-minor-version-52-0

**Comment by pnrobinson** [comment]
This is working fine on my mac, I think that this must be an old Java version!

**Comment by hansenp** [comment]
Also Sala is not able to run GOPHER on his mac. The java version is:

![image](https://user-images.githubusercontent.com/10495485/44657160-3c1a2800-a9fc-11e8-8fa2-b1785c29e607.png)

This is the error message:

![image](https://user-images.githubusercontent.com/10495485/44657344-ccf10380-a9fc-11e8-8f34-16eee1fc4c27.png)

**Comment by pnrobinson** [comment]
hm... it looks as is Sala has Java 10.
Some people have been having this issue.
https://www.reddit.com/r/learnjava/comments/73fldw/newcome_question_unable_to_run_eclipse/
I think we need to finish the remaining four issues and then probably install Java 10 and check this....
-

**Comment by steinha** [comment]
I have both Java 8 and Java 10 JREs installed. Some apps run only with Java 8 (e.g., ``JabRef``), some with both Java 8 and Java 10. A graceful error message would be nice feature. 

![image](https://user-images.githubusercontent.com/5254933/44657783-5d7c1380-a9fe-11e8-9d15-8c8f28d34c58.png)

**Comment by pnrobinson** [comment]
Does GOPHER run on your Java10 JRE?

**Comment by pnrobinson** [comment]
It would be easy to write an error message if we cannot figure out how to get GOPHER to run on Java 9 or 10:
```
String version = System.getProperty("java.version");
```

**Comment by steinha** [comment]
Trying to run release 0.4.7 on my Java 10 JRE generates the same exception as on Sala's Mac.

**Comment by hansenp** [comment]
Uwe's java version:

![image](https://user-images.githubusercontent.com/10495485/44662562-75f42a00-aa0e-11e8-960f-2a0547a0131b.png)

**Comment by steinha** [comment]
BTW: It is possible to create multi-release JAR files. http://openjdk.java.net/jeps/238

**Comment by hansenp** [comment]
I checked the version of Uwe's mac using the terminal. It turned out that Java 1.6 is installed on his mac even though the graphical interface reports Java 1.8 to be installed.

**Comment by hansenp** [comment]
Would Docker also be an option to solve this issue?

**Comment by pnrobinson** [comment]
Largely fixed/addressed by recent commits. We will consider a bundling solution if necessary depending on future testing.
