### ISSUE TITLE
Change URL for embedded UCSC tracks

### ISSUE THREAD

**Issue by hansenp** [TheJacksonLaboratory/Gopher#277]
In many cases the precise location of the TSS cannot be inferred from the embedded UCSC track for refSeq genes is shown in _dense_ representation mode. Furthermore, the gene name is not displayed in _dense_ mode.

Therefore, the representation mode should be changed to _packed_ for the embedded tracks as well as for the URL that can be copied to the clipboard.

**Comment by pnrobinson** [comment]
I do not understand this. We have set the refgene to full
```
refGene=full
```
ideas? @hansenp

**Comment by pnrobinson** [comment]
This needs to be replaced with 
ncbiRefSeqView=full

**Comment by pnrobinson** [comment]
Also for alignability!

**Comment by hansenp** [comment]
Since we will use self-prepared maps that are slightly different from maps available in UCSC, we should remove alignability from the URL because it might confuse users if the score of probes is not consistent with the displayed map.

In the medium term, we could deposit bigWig files for the self-prepared map at our ftp server. It's possible to load external data in UCSC via URL. See here: http://charite.github.io/Q/tutorial.html#visualization

**Comment by pnrobinson** [comment]
@hansenp I cannot get the alignability to appear within GOPHER. Not sure I understand the URL.
This does not appear to be sufficient:
```
g=wgEncodeCrgMapabilityAlign50mer&i=wgEncodeCrgMapabilityAlign50mer
```
I am also seeing l, r, o, and t arguments -- maybe they need to be passed also. Any idea where to find this? Maybe we should leave this out of the GOPHER code for now.

**Comment by pnrobinson** [comment]
I think we agreed to close this for now. The embedded images look great, and we will need to figure out a way to disply the alignability maps in them as well.
