### ISSUE TITLE
Memory issues documentation

### ISSUE THREAD

**Issue by pnrobinson** [TheJacksonLaboratory/Gopher#284]
THis is a bit out of date, but we should add something like this to the trouble shooting page.
http://pcgen.org/autobuilds/pcgen-docs/faqpages/faqoutofmemoryandjavaissues.html

**Comment by steinha** [comment]
Can we catch the ``OutOfMemoryError`` exception and display a proper error message? On my test machine even with very simple queries, without the ``-Xmx`` option, GOPHER immediately runs out of memory and continues to display the ``Creating viewpoints using ...`` dialog. 

![memory](https://user-images.githubusercontent.com/5254933/44774477-81ad3100-ab73-11e8-92ca-6f657d207b81.gif)

**Comment by steinha** [comment]
It would also be possible I think to have GOPHER detect its heap size and/or try to relaunch itself with a larger heap size...

**Comment by steinha** [comment]
Alternatively, we could ship GOPHER with ``Run_GOPHER_Unix.sh`` and ``Run_GOPHER_Win.bat`` scripts (similar to FABIAN) that detect if Java 8 is installed and launch ``GopherGui-0.5.0.jar`` with an appropriate heap option.

**Comment by pnrobinson** [comment]
I have been trying to put the viewpoint creation thread in a try catch block with this
```
 } catch (OutOfMemoryError ooem) {
            MemoryMXBean memoryBean = ManagementFactory.getMemoryMXBean();
            MemoryUsage heapMemory = memoryBean.getHeapMemoryUsage();
            MemoryUsage nonHeapMemory = memoryBean.getNonHeapMemoryUsage();
            String format = "%-15s%-15s%-15s%-15s";
            StringBuilder sb = new StringBuilder();

            sb.append(String.format(format, "COMMITTED", "INIT", "USED", "MAX")).append("\n");
            sb.append(String.format(format,
                    NumberFormat.getInstance().format(heapMemory.getCommitted()),
                    NumberFormat.getInstance().format(heapMemory.getInit()),
                    NumberFormat.getInstance().format(heapMemory.getUsed()),
                    NumberFormat.getInstance().format(heapMemory.getMax()))).append("\n");


            sb.append("NON-HEAP MEMORY").append("\n");
            sb.append(String.format(format, "COMMITTED", "INIT", "USED", "MAX")).append("\n");
            sb.append(String.format(format,
                    NumberFormat.getInstance().format(heapMemory.getCommitted()),
                    NumberFormat.getInstance().format(heapMemory.getInit()),
                    NumberFormat.getInstance().format(heapMemory.getUsed()),
                    NumberFormat.getInstance().format(heapMemory.getMax()))).append("\n");
            ooem.printStackTrace();
            System.err.println(sb.toString());
        }
```
but it is not possible to cast an OutOfMemoryError to an Exception (for good reasons). 
It might be possible to have GOPHER check the alloted memory with getCommitted() and to issue a warning if it is not enough (before the user tries to run createViewpoints -- everything else does not require that much memory).

**Comment by pnrobinson** [comment]
Thanks -- I implemented this and also added some documentation to the RTD.

**Comment by steinha** [comment]
@pnrobinson, FYI – This is what the error message looks like on Windows in the current commit:
![image](https://user-images.githubusercontent.com/5254933/44796430-462f5880-abad-11e8-84af-2a980ff59555.png)

**Comment by pnrobinson** [comment]
Also on linux. The dialog is not showing text, but the title should be sufficient....
