### ISSUE TITLE
GOPHER crashes with no “gopher” directory

### ISSUE THREAD

**Issue by steinha** [TheJacksonLaboratory/Gopher#287]
When you remove or rename the ``gopher`` directory from the home path, GOPHER will not start on Windows (InvocationTargetException). This affects release 0.5.0.

The offending code is below, because ``files`` will be ``null``:
https://github.com/TheJacksonLaboratory/Gopher/blob/979a9279451a5244d9edb691a3f4ff119a54e7a2/src/main/java/gopher/gui/splash/SplashPresenter.java#L79-L92

**Comment by pnrobinson** [comment]
I added this
```
ObservableList<String> lst = FXCollections.observableArrayList();
File dir = getGopherDir();
if (dir==null) return lst;
File[] files = dir.listFiles(pathname -> pathname.getAbsolutePath().endsWith(".ser"));
if (files==null) return lst;
```
@steinha please test version 0.5.1,

**Comment by steinha** [comment]
GOPHER version 0.5.1 now starts even when there is no ``gopher`` directory in the home path.

However, an error now occurs when the user tries to save a new project (``Ctrl+S``) and there is no ``gopher`` directory in the home path:
![image](https://user-images.githubusercontent.com/5254933/44784183-09ec0000-ab8d-11e8-99d2-fd8c8494affd.png)

**Comment by pnrobinson** [comment]
That's strange, I thought that Gopher would make a .gopher directory if it cannot find one. I will test here!

**Comment by pnrobinson** [comment]
For some reason, GOPHER is creating a directory called `` .gopher.Gopher`` instread of ``.gopher``. It cannot therefore not find the right directory.

**Comment by steinha** [comment]
The GOPHER directory on Windows used to be ``%userprofile%\gopher`` (e.g., ``C:\Users\User\gopher``). 

If possible, I would try to avoid naming any file or directory beginning with a period on Windows. It is not even possible in Windows Explorer (without tricks). 

![image](https://user-images.githubusercontent.com/5254933/44799563-880fcd00-abb4-11e8-9a3a-a45d438b2b66.png)

**Comment by hansenp** [comment]
On my Linux computer I have both directories `/home/.gopher` and `/home/.gopher.Gopher`. The directory `/home/.gopher.Gopher` has the following content:

`.gopher.Gopher/webview/localstorage/http_gopher.readthedocs.io_0.localstorage`

**Comment by hansenp** [comment]
If I rename the GOPHER directories, open, create a new project and try to save via _File_ menu or `ctrl-s`, I get the following error message:

![image](https://user-images.githubusercontent.com/10495485/44845062-d375ba00-ac4c-11e8-8bfb-c6de1d99cf82.png)

**Comment by pnrobinson** [comment]
Please delete all of the .gopher directories and try to start. This causes an error on my machine. There is something that is causing Gopher to create a directory called .gopher.Gopher instread of simply .gopher and this is causing the error.

**Comment by hansenp** [comment]
I think this solves this issue, right?

I found out that the .gopher.Gopher directory is created in `PopupFactory.java` here:

![image](https://user-images.githubusercontent.com/10495485/44849697-425a0f80-ac5b-11e8-8069-9a6994014864.png)

in line 98.

**Comment by pnrobinson** [comment]
Thanks -- Daniels branch fixed the lack of the .gopher directory.
Still there are two outstanding problems
@hansenp @ielis please take a look
1. GOPHER is still making a .gopher.Gopher directory in the new project -- we do not need to create two directories
2. @steinha suggested we do not use a leading period for the window directory, but I am not sure -- 
shouldnt we get ``%userprofile%\gopher`` with the code
```
System.getProperty("user.home") + File.separator + "gopher"
```
if so then this is OK.
I merged this branch already sorry

**Comment by ielis** [comment]
I think the `gopher.Gopher` directory is created by classes `javafx.scene.web.WebEngine` which is used in `PopupPresenter`. It looks like these *html-rendering* classes create a directory derived from classname (in this case `gopher.Gopher`) where they are used and then store some content in the directory (info from here [WebEngine.userDataDirectoryProperty()](https://docs.oracle.com/javase/8/javafx/api/javafx/scene/web/WebEngine.html#userDataDirectoryProperty). 

I will take a closer look at this and try to fix it.

**Comment by steinha** [comment]
@pnrobinson, regarding your second point: Yes, the code separates between Windows and Unix. It is fine.

https://github.com/TheJacksonLaboratory/Gopher/blob/5bf549c853ace24752719860d7f31beedde74f0f/src/main/java/gopher/io/Platform.java#L38-L53

**Comment by pnrobinson** [comment]
OK -- if this is the case, then it is not a major issue, I thought that our code was somehow creating this. If there is not really easy solution to it, then we can probably just ignore it.

**Comment by pnrobinson** [comment]
fixed
