### ISSUE TITLE
Titles in GUI are not aligned again

### ISSUE THREAD

**Issue by steinha** [TheJacksonLaboratory/Gopher#288]
![image](https://user-images.githubusercontent.com/5254933/44773103-f7af9900-ab6f-11e8-8a3d-5bfd838c75c5.png)

**Comment by pnrobinson** [comment]
The "margin" -fxml was not correct. I fixed this.

**Comment by steinha** [comment]
The titles are fixed in version 0.5.1 but the gray bar before ``Data sources`` is still shorter than the other two:
![image](https://user-images.githubusercontent.com/5254933/44785987-fb084c00-ab92-11e8-9a52-4ad42fe49f04.png)
