### ISSUE TITLE
GOPHER displays 'null' for version number

### ISSUE THREAD

**Issue by hansenp** [TheJacksonLaboratory/Gopher#291]
If I click on _Help_ and then _About_ a window pops up that is intended to show the number of the current version of GOPHER. The displayed version is _null_.

![image](https://user-images.githubusercontent.com/10495485/44839871-1c734180-ac40-11e8-865e-2613f8e63edf.png)

**Comment by pnrobinson** [comment]
if we build gopher with maven the correct version number is shown. This is not a bug, but we need to remember to build with maven prior to releases
