### ISSUE TITLE
Logging-

### ISSUE THREAD

**Issue by pnrobinson** [TheJacksonLaboratory/Gopher#301]
For the final release, we should set the logging level to the console to be ERROR, and the logging to the file to be debug (the user can change it to trace if there are any problems)
There are probably too many irrelevant logging statements still in the code that will not help much with debugging at a distance, but it should not be a performance problem.

**Comment by steinha** [comment]
On my computer, opening the log (Help > Show log) is not working.
In version 0.5.1, the ``goper.log`` file appears to be created in the same folder as the ``GOPHER-0.5.1.jar`` and not in ``%userprofile%\gopher``.

![image](https://user-images.githubusercontent.com/5254933/44906816-44cd6f80-ad16-11e8-96b4-7ecd30826384.png)

**Comment by pnrobinson** [comment]
@steinha -- I wonder if this bug was related to the spaces-in-paths bug that we (probably) fixed. Could you try this again? The log function is working fine on my linux and mac boxes.

**Comment by pnrobinson** [comment]
I deleted my .gopher directory and was able to reproduce this bug. I changed the way GOPHER figures out where to log to and now it is working on my computer. Please reopen if the bug is persisting under windows (it should be ok!)

**Comment by pnrobinson** [comment]
set level to ERROR.
