### ISSUE TITLE
Loading a previous project does not populate targetGeneLabel

### ISSUE THREAD

**Issue by steinha** [TheJacksonLaboratory/Gopher#303]
After loading a previous project, ``targetGeneLabel`` remains empty. It does get populated when clicking on ``Target gene list`` and then ``Cancle``. See clip below.

``allGenesLabel`` and ``bedTargetsLabel`` appear to be affected in the same way.

![genelable](https://user-images.githubusercontent.com/5254933/44906074-3a11db00-ad14-11e8-8258-8b529744fdd9.gif)

**Comment by pnrobinson** [comment]
Fixed this!
