### ISSUE TITLE
Canceling project export raises InvocationTargetException

### ISSUE THREAD

**Issue by steinha** [TheJacksonLaboratory/Gopher#305]
``File > Export project ...`` 

Offensive code (``file`` will be ``null``):

https://github.com/TheJacksonLaboratory/Gopher/blob/ed50ff0fe04cea837da75b5e1c99eb97f2c7e421/src/main/java/gopher/gui/gophermain/GopherMainPresenter.java#L1431-L1442

**Comment by pnrobinson** [comment]
fixed
