### ISSUE TITLE
Accidentally typing text into number fields raises RuntimeException

### ISSUE THREAD

**Issue by steinha** [TheJacksonLaboratory/Gopher#309]
Uncaught exception immediately after typing ``a``: 
![image](https://user-images.githubusercontent.com/5254933/44912773-97655680-ad2b-11e8-8a94-71af5f54de9a.png)

No exception:
![image](https://user-images.githubusercontent.com/5254933/44910830-f1165280-ad24-11e8-93e8-9b89b443f62f.png)

This affects all number fields as far as I can tell.

---

Additionally, when loading a previous project manually via ``File > Import project ...``, GOPHER suddenly automatically adds thousands separators to number fields, which can lead to an uncaught ``IllegalArgumentException``:

![numberfield](https://user-images.githubusercontent.com/5254933/44911702-0fca1880-ad28-11e8-9da9-52d49992a4be.gif)

**Comment by pnrobinson** [comment]
I think that this technique will work -- and we will show it in red when the user is about to make viewpoints if one of the values is bad
https://stackoverflow.com/questions/50208585/javafx-bind-bidirectional-with-numberconverter

**Comment by pnrobinson** [comment]
Seems to work now!
