### ISSUE TITLE
Model is saved on quit without warning

### ISSUE THREAD

**Issue by steinha** [TheJacksonLaboratory/Gopher#310]
Right now, ``serialize()`` is called when the user selects ``yes`` in either of the prompts below. That is not intuitive. How to quit GOPHER without saving the model?

Additionally, deleting or editing viewpoints does not clear the ``model.clean`` flag and therefore will not trigger the ``Unsaved work`` prompt.

![image](https://user-images.githubusercontent.com/5254933/44917519-d5b54280-ad38-11e8-938f-93effd904809.png)
![image](https://user-images.githubusercontent.com/5254933/44917813-b539b800-ad39-11e8-92a8-e505cf188a6a.png)

https://github.com/TheJacksonLaboratory/Gopher/blob/ed50ff0fe04cea837da75b5e1c99eb97f2c7e421/src/main/java/gopher/gui/gophermain/GopherMainPresenter.java#L1553-L1569

**Comment by pnrobinson** [comment]
I have added a new dialog with the buttons
Save and quit
Just quit
cancel

I have also made sure that deleting or editing viewpoints sets model.clean to FALSE

**Comment by steinha** [comment]
According to TRACE messages, ``serialize()`` is still called when the user selects ``Just quit`` on the new prompt, and ``serialize()`` is called twice when the user selects ``Save and quit``. This line needs to be removed I think:

https://github.com/TheJacksonLaboratory/Gopher/blob/660bc12ba60ba00d86d18156d14a7d149d9aaa3c/src/main/java/gopher/gui/gophermain/GopherMainPresenter.java#L1600

Additionally, FYI: Resetting a viewpoint does not clear the ``model.clean`` flag.

**Comment by pnrobinson** [comment]
Ups! My dumb, I fixed this again. :-0
I also added some code to set clean to false if resetting the viewpoint changes its state (I call the ViewPoint.wasModified function to check this).
