### ISSUE TITLE
Score does not revert when segments are deselected

### ISSUE THREAD

**Issue by steinha** [TheJacksonLaboratory/Gopher#311]
See example in clip below. The score for the default segment is ``85.61%``. When another segment is added, the score increases to ``99.99%``. When the other segment is removed again, the score remains at ``99.99%`` and the viewpoint is not marked as manually revised.

This affects many or all viewpoints.

![score](https://user-images.githubusercontent.com/5254933/44923816-ab1fb580-ad49-11e8-9a45-fc0cc0f5dcf2.gif)

**Comment by steinha** [comment]
Another example. Maybe recalculation is triggered only when a segment is added, not when a segment is removed?

![score2](https://user-images.githubusercontent.com/5254933/44924956-2a62b880-ad4d-11e8-881f-ad90dac32c10.gif)

**Comment by pnrobinson** [comment]
Viewpoint.refreshStartAndEndPos does not seem to be resetting the start position after you deselect a segment, even though the segment has selected==false.

**Comment by pnrobinson** [comment]
There was a bug in refreshStartAndEndPos. The following two commands were in the for loop but should not have been
```
 this.setStartPos(min);
 this.setEndPos(max);
```
I changed this and now things work correctly!
