### ISSUE TITLE
“Open Image in New Window” does nothing

### ISSUE THREAD

**Issue by steinha** [TheJacksonLaboratory/Gopher#312]
This does nothing. The menu is displayed with right-click:

![image](https://user-images.githubusercontent.com/5254933/44924501-c4c1fc80-ad4b-11e8-87ff-794369be7714.png)

**Comment by pnrobinson** [comment]
I think this is coming from the UCSC Browser and not from our code. The copy image to Clipboard seems to work at least. I have not seen any documentation about how to get rid of this, and think it might be difficult to do. I do not think this is a major problem and I will close this issue next week unless anybody else has an idea of what to do here.

**Comment by pnrobinson** [comment]
Let's leave this one, it is difficult and low priority!
