### ISSUE TITLE
Mean score and mean size in “Panel design summary”

### ISSUE THREAD

**Issue by steinha** [TheJacksonLaboratory/Gopher#313]
It makes more sense to show the score in percent. Below, ``0.4`` means ``43.38%``.

![image](https://user-images.githubusercontent.com/5254933/44925550-030ceb00-ad4f-11e8-9298-a01c7698fdbe.png)

---

Additionally, does it make sense to include viewpoints with no segments in the mean size and mean score calculation?

![image](https://user-images.githubusercontent.com/5254933/44925903-fd63d500-ad4f-11e8-84be-985831e30a8f.png)

**Comment by pnrobinson** [comment]
I have adjusted this to show e.g. 34.6% in both displays (two positions after the decimal point was too much!).
I would say that we should include all viewpoints in the calculate of the mean size etc, since users will want to know if the overall average score is really that bad.
