### ISSUE TITLE
Project file names cannot contain spaces

### ISSUE THREAD

**Issue by steinha** [TheJacksonLaboratory/Gopher#314]
However, GOPHER does list them. I noticed this when trying to load a project file which I had previously created a copy of. On Windows, this appends ``- Copy`` to the file name before the extension.

Files (``%userprofile%\gopher``):
![image](https://user-images.githubusercontent.com/5254933/44926296-449e9580-ad51-11e8-83b4-ea6b80133ae9.png)

GOPHER menu:
![image](https://user-images.githubusercontent.com/5254933/44926257-233da980-ad51-11e8-8331-3ae8c9ce37fc.png)

Error:
![image](https://user-images.githubusercontent.com/5254933/44926398-91826c00-ad51-11e8-8396-d27c6950948c.png)

**Comment by pnrobinson** [comment]
I think I implemented a function to replace spaces with underscores -- spaces in paths always seem difficult, at least with linux. Is this an issue for Windows users?

**Comment by steinha** [comment]
Windows developers often have no choice but to handle paths with spaces because the default program directory is ``C:\Program Files\``.

If GOPHER cannot handle file names with spaces, maybe these names should not appear in the project list (“GOPHER menu” above).

**Comment by steinha** [comment]
We should test if GOPHER still works when ``%userprofile%`` resolves to something like ``C:\Users\Max Mustermann``. I will do it.

**Comment by steinha** [comment]
I created a new user *Max Mustermann* on Windows 10. Unfortunately, the error below occurred when I tried to save the project. On first start, GOPHER did create the working directory ``C:\Users\Max Mustermann\gopher``.

![image](https://user-images.githubusercontent.com/5254933/44948835-4df93200-ae25-11e8-8a9f-9901234a0c44.png)

**Comment by steinha** [comment]
Yes, this works on Windows, too. 

Note the following, which are not high-priority issues in my opinion:

* There appears to be no check whether the project name contains characters not allowed in filenames (e.g., ``\ / * < >``), so these projects can be created but not saved
* There appears to be no check whether a project name already exists, so a previous project file may get overwritten without warning

Fine to close this issue.

**Comment by pnrobinson** [comment]
Good suggestion -- I implement the above two criteria.
