### ISSUE TITLE
Settings report is a subset of GOPHER report

### ISSUE THREAD

**Issue by steinha** [TheJacksonLaboratory/Gopher#316]
Does GOPHER need both? The Settings report has a nicer format.

Settings report: ``Edit > Show settings of current project``
GOPHER report: ``Export > Display report``

**Comment by pnrobinson** [comment]
People might not think to show the Report before they have done the analysis and want to check the settings...I am not sure what is best here. The report format could be made nicer but then it would be harder to copy paste...

**Comment by steinha** [comment]
Neither report can be copied right now. The only option is to export the GOPHER report.

**Comment by pnrobinson** [comment]
I think that we should probably leave this for now. There are situations when the user might want to see all of the settings before the report is ready.
