### ISSUE TITLE
Order of obtaining data sources

### ISSUE THREAD

**Issue by steinha** [TheJacksonLaboratory/Gopher#318]
I'm not sure new users will understand they have to obtain data sources in a specific order. Some users may try to index the genome after selecting the genome build (*left-to-right, top-to-bottom*). In this case, the error message is not very helpful and the path does not even make sense (no directory ``C:\Users\...\Programs\Gopher\null`` exists).

![image](https://user-images.githubusercontent.com/5254933/44935381-c356fb00-ad70-11e8-84a8-95344ef18b57.png)

![image](https://user-images.githubusercontent.com/5254933/44935628-c7374d00-ad71-11e8-85b2-0cc13dcd09ee.png)

**Comment by pnrobinson** [comment]
Good point. I added better warnings!
