### ISSUE TITLE
Sign the jar

### ISSUE THREAD

**Issue by pnrobinson** [TheJacksonLaboratory/Gopher#319]
https://docs.oracle.com/javase/tutorial/deployment/jar/signing.html

**Comment by pnrobinson** [comment]
After some research, I am less sure we want to do this -- getting a "trustworthy" certificate will cost a decent amount and a "free" certificate probably does not provide much security. At this point I do not think we are that likely to be targeted by scammers.

**Comment by steinha** [comment]
Charité operates a public key infrastructure in corporation with Deutsche Forschungsnetz (DFN). Perhaps they can help. https://intranet.charite.de/it/it_serviceueberblick/charite_pki/
