### ISSUE TITLE
Revising a viewpoint resets viewpoint order in Analysis tab

### ISSUE THREAD

**Issue by steinha** [TheJacksonLaboratory/Gopher#320]
![order](https://user-images.githubusercontent.com/5254933/44955043-12a24600-aead-11e8-8817-7516e5812ce3.gif)

**Comment by pnrobinson** [comment]
After fixing #311 I cannot reproduce this error anymore. @steinha @hansenp -- please check
I would also say that some rearrangement of the list would be OK, e.g., if we are sorting by score.

**Comment by steinha** [comment]
I can still reproduce it.

In which order are viewpoints listed in the Analysis tab by default? It looks like *lexicographically by chromosome* (e.g., ``chr1:..``, ``chr10:..``, ..., ``chr19:..``, ``chr2:..``, ``chr20:..``). Within the same chromosome, I could not determine an order.

I think it could frustrate some users when they order viewpoints (e.g., by gene as in the clip), revise a viewpoint (e.g., by clicking ``Reset``) and loose the order (i.e., viewpoint is suddenly below the fold).

**Comment by pnrobinson** [comment]
Thanks, this works on my side!
