### ISSUE TITLE
Align numbers right on Analysis tab

### ISSUE THREAD

**Issue by steinha** [TheJacksonLaboratory/Gopher#321]
Right-aligned numbers are easier to read and compare.

![image](https://user-images.githubusercontent.com/5254933/44955188-ab39c580-aeaf-11e8-911b-15f780451bab.png)

E.g., see Viewpoint tab:

![image](https://user-images.githubusercontent.com/5254933/44955193-cd334800-aeaf-11e8-9630-df3ce0d4dfc7.png)

**Comment by pnrobinson** [comment]
Fixed this. I also put Fragment at TSS right aligned -- I could not get it to go in the center, but this is not a big issue.
