### ISSUE TITLE
Cannot input coordinates in BED6 format

### ISSUE THREAD

**Issue by hansenp** [TheJacksonLaboratory/Gopher#324]
When I try to read the following coordinates from a BED6 formated file:

`chr1    249240000   249240000   GEOC1   0   +`

I'm getting the following exception:

![image](https://user-images.githubusercontent.com/10495485/45036937-11fce180-b05e-11e8-9f4d-364bb34bc8fe.png)

**Comment by pnrobinson** [comment]
The file had spaces and no tab!
But -- there was another bug in that if a file had a new line after the last data line, Gopher tried to parse the following empty line and this caused it to parse. I added a check for this and now BED parsing should work.
