### ISSUE TITLE
retro font -- modernize (setup tab)

### ISSUE THREAD

**Issue by pnrobinson** [TheJacksonLaboratory/Gopher#325]

**Comment by hansenp** [comment]
I just noted that we have screenshots of the setup tab in the manuscript.

**Comment by pnrobinson** [comment]
changed the font. This is probably not critical for the manuscript but I will leave this open for now in case we want to redo Figure 1

**Comment by steinha** [comment]
Helvetica is not available on Windows. It gets replaced with Arial in the lastest GOPHER version as far as I can tell.

![image](https://user-images.githubusercontent.com/5254933/45095861-66b46100-b11f-11e8-93b1-825289ed7ec3.png)

**Comment by pnrobinson** [comment]
Arial is not too bad?
But is there a good font that works on all platforms?

**Comment by steinha** [comment]
Not sure. We could bundle one of the Google Fonts (https://fonts.google.com/) with the ``.jar`` and use that. I think they are all free-to-use.

**Comment by pnrobinson** [comment]
ggf at the revision
