### ISSUE TITLE
Inconsistent lists of initial/all digests for extended approach and different settings of Allow unbalanced?

### ISSUE THREAD

**Issue by hansenp** [TheJacksonLaboratory/Gopher#329]
If I run GOPHER with the extended approach and default settings on GATA1, there are 15 digest in the list of all digests.

<img width="1185" alt="screen shot 2018-09-05 at 7 16 07 am" src="https://user-images.githubusercontent.com/10495485/45089881-9d688800-b0db-11e8-98bc-46d383eca42e.png">

If I select Allow unbalanced?, the list contains two additional digests in downstream direction.

<img width="1187" alt="screen shot 2018-09-05 at 7 26 19 am" src="https://user-images.githubusercontent.com/10495485/45090362-2633f380-b0dd-11e8-94c4-662e7fbb2413.png">

**Comment by pnrobinson** [comment]
l.582 in Viewpoint -- we will comment them out.
