### ISSUE TITLE
Illegal character in source file names

### ISSUE THREAD

**Issue by steinha** [TheJacksonLaboratory/Gopher#337]
A colon may not appear in file names in Windows. Therefore, unzipping the source archive generates two errors.

Directory: https://github.com/TheJacksonLaboratory/Gopher/tree/master/src/test/resources/smallgenome

![image](https://user-images.githubusercontent.com/5254933/45227545-0eb56000-b2c1-11e8-8c38-0e9d047f4460.png)

![image](https://user-images.githubusercontent.com/5254933/45227551-12e17d80-b2c1-11e8-8214-f766d8ca76f5.png)

**Comment by pnrobinson** [comment]
I have changed these file names!
