### ISSUE TITLE
Setup tab is not properly loaded after “Ctrl+N”

### ISSUE THREAD

**Issue by steinha** [TheJacksonLaboratory/Gopher#344]
This is related to issue #257. Creating a new project from a previously saved project with ``Ctrl+N`` does not properly reset the Setup tab.

Steps to reproduce: 

- Create a new project in the ``Welcome to GOPHER`` dialog.
- Set Genome build to mm10
- ``Ctrl+S``
- ``OK``
- ``Ctrl+N``
- Type a new project name
- ``OK``

Result: Genome build not reset to hg19 and all design parameters cleared (light gray text). 

![image](https://user-images.githubusercontent.com/5254933/45265898-c29a2500-b452-11e8-91a8-7d54a80e18b8.png)

**Comment by pnrobinson** [comment]
I added this to the reset function
```
 genomeChoiceBox.getSelectionModel().selectFirst();
```
and then you get hg19 when you create a new project

**Comment by steinha** [comment]
@pnrobinson, Commit 3d42fca addresses part of this issue. The design parameter fields are still cleared (see below). The Approach drop-down list is also not reset to ``Simple``.

![reset](https://user-images.githubusercontent.com/5254933/45283266-b018fd80-b4dd-11e8-9def-e3eeca9fb752.gif)

Additionally, pressing ``Create viewpoints!`` in the new project immediately raises an uncaught exception:

```
Exception in thread "JavaFX Application Thread" java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at javafx.fxml.FXMLLoader$MethodHandler.invoke(FXMLLoader.java:1774)
...
Caused by: java.lang.NullPointerException
	at gopher.gui.gophermain.GopherMainPresenter.percentageToProportion(GopherMainPresenter.java:751)
	at gopher.gui.gophermain.GopherMainPresenter.updateModel(GopherMainPresenter.java:731)
	at gopher.gui.gophermain.GopherMainPresenter.createViewPoints(GopherMainPresenter.java:1223)
...
```

**Comment by pnrobinson** [comment]
sorry, this was incomplete, reopening

**Comment by hansenp** [comment]
Maybe this is related to this issue. If I select the _Data sources_ for hg38, save and reopen the project. The genome build is switched back to hg19 and all _Data sources_ are gone.

![iss344](https://user-images.githubusercontent.com/10495485/45358226-0878f980-b5c9-11e8-9af5-34133ac968dc.gif)

**Comment by pnrobinson** [comment]
The design parameter fiels seem to be set back to their defaults. Another recent commit fixed the bug with the null pointer exception. It is intentional that the download fields are clearer -- it is a new project after all.

**Comment by steinha** [comment]
@pnrobinson, The design parameter fields appear to be cleared, set to (nothing). The defaults shimmer in the background (light gray text). Try clicking into one.

![image](https://user-images.githubusercontent.com/5254933/45472153-a4267900-b733-11e8-91d3-09504b53a774.png)

**Comment by pnrobinson** [comment]
This is the intended behavior -- the user can use the prompts if he or she likes. If you click on createViewpoints after you have set the genome and other files but leave all of this as default, then the default values are chosen correctly. The purpose of the grey prompt text is to get people to think consciously about whether they want the default values or not.
 @steinha  -- is there a better way of doing this?

**Comment by steinha** [comment]
Ideally the parameter fields should look and behave the same:

- When a new project is created via the Welcome dialog
![image](https://user-images.githubusercontent.com/5254933/45484061-2ecaa080-b753-11e8-8cee-a84002220b08.png)

- When a new project is created via ``Ctrl+N``
![image](https://user-images.githubusercontent.com/5254933/45484079-42760700-b753-11e8-8243-944706c77b53.png)

I have learned that parameter fields with default values change text color from light-gray to black when the user creates viewpoints, then saves the project, closes GOPHER and then loads the project. This behavior is fine in my opinion. (This is depicted as *Normal* in the screenshot above.)

**Comment by pnrobinson** [comment]
OK, now I understand (at least I think so!)
I have unified the way the GUI is initialized so that it is the same for both ways of creating a new project, and now the dialog is the same for both!
