### ISSUE TITLE
Sorting of number columns is lexicographical

### ISSUE THREAD

**Issue by steinha** [TheJacksonLaboratory/Gopher#346]
Affects all number and percentage columns in both Analysis and Viewpoint tabs as far as I can tell.

![image](https://user-images.githubusercontent.com/5254933/45370734-1e96b200-b5e9-11e8-906d-5dddc4a87fd4.png) ![image](https://user-images.githubusercontent.com/5254933/45370835-5bfb3f80-b5e9-11e8-9a32-e01e146fd135.png)

**Comment by hansenp** [comment]
Now, the column #Selected on the analysis tab is sorted numerically, and sorting is deactivated for all columns on the viewpoint tab.

@steinha: Do you think this is ok now?

**Comment by steinha** [comment]
Looks good to me.
