### ISSUE TITLE
Add Block-Approach

### ISSUE THREAD

**Issue by hansenp** [TheJacksonLaboratory/Gopher#359]
Capture Hi-C is sometimes used to target a small number of larger regions (e.g. with lengths of about 1Mbp). So far, this use case  is not supported. As a workaround, the user can use the _Enter BED file_ button, upload a list of single positions and use large arguments for _Up_- and _Downstream size_. However, this approach results in viewpoints with a uniform size and the uploaded positions are in the center, which might not be optimal from a biological point of view.

It should be possible to upload a BED file with viewpoint start and end coordinates to GOPHER. Fragments and probes are then created as for the simple or extended approach.

**Comment by pnrobinson** [comment]
This is not priority enough to follow up now, closing.
