### ISSUE TITLE
Update read the docs to explain format of digest file that is exported by GOPHER

### ISSUE THREAD

**Issue by pnrobinson** [TheJacksonLaboratory/Gopher#361]

**Comment by hansenp** [comment]
We could take this from the Diachromatic documentation:

https://diachromatic.readthedocs.io/en/latest/digest.html

**Comment by pnrobinson** [comment]
done
@hansenp  note that the documentation is not quite correct
Please see the new page, Enrichment status was changed to Enrichment_status for consistency
