### ISSUE TITLE
Enable digest selection via upload of BED file bypassing selection via approaches

### ISSUE THREAD

**Issue by hansenp** [TheJacksonLaboratory/Gopher#363]
There might be users that did not use GOPHER for probe design but do want to use `Diachromatic` for downstream analysis. In such cases, a GOPHER digest file has to be prepared that can be passed to `Diachromatic` using the `-d` option.

The digest file can be exported from GOPHER before creation of probes. In this case, all digests are declared to be unselected (`F` in column 12).

There should be an additional export option that allows to bypass the design process by uploading a BED file with viewpoint coordinates. All digests covered by viewpoints should then be declared to be selected.

**Comment by pnrobinson** [comment]
I think this is superseded by the development of diachromatic since 2019, closing.
