### ISSUE TITLE
Add prefix to downloaded refGene.txt.gz and chromInfo.txt.gz

### ISSUE THREAD

**Issue by hansenp** [TheJacksonLaboratory/Gopher#368]
In order to download the input files for GOPHER, the user has to specify separate paths for:

1. the reference sequence in FASTA format
2. the annotation refGene.txt.gz file
3. the alignability map calculated by GEM (file with chromosome sizes will also be downloaded)

Usually, the user will specify the same path in all three cases. The files for reference sequence and alignability are prefixed with the shorthand symbol of the corresponding genome build (e.g. hg38), but the files for annotation and chromosome sizes have no prefix, i.e. they have the same name for all genome builds.

<img width="298" alt="Screen Shot 2019-07-23 at 7 46 09 AM" src="https://user-images.githubusercontent.com/10495485/61709798-feae3f80-ad1d-11e9-8a4c-9e65907b21ba.png">

This can easily lead to application errors. For instance, if the user specifies a directory for the wrong genome build that already contains a `refGene.txt.gz` file. In such cases, GOPHER won't download a new file, but instead will use the existing file that corresponds to a different genome build.

Ideally, the user has to specify only one data path for each project and all files should be prefixed with the corresponding genome build.

**Comment by pnrobinson** [comment]
Using the wrong genome will lead to an error about incorrect sequence length. We have not received complaints about this since 2019 and so I am guessing Gopher users have figured this out. Closing for now, we can reopen if we ever do a version 2 with more features etc.
