### ISSUE TITLE
can't set custom probe length

### ISSUE THREAD

**Issue by golova-n** [TheJacksonLaboratory/Gopher#369]
when trying to set 140bp probe length, output probe length still remains 120bp
Thank you for help

**Comment by pnrobinson** [comment]
Could you perhaps send us a screenshot of your settings and one or two lines of the output file? If you would prefer to do so by email that's fine, our emails are in the paper

**Comment by hansenp** [comment]
I fixed this and published 'GOPHER release 0.6.2' that allows to export probes with custom length:

https://github.com/TheJacksonLaboratory/Gopher/releases/tag/v0.6.2
