### ISSUE TITLE
Add genes/TSS to the output digest file

### ISSUE THREAD

**Issue by pnrobinson** [TheJacksonLaboratory/Gopher#372]
Add information about the gene and the chromosomal position of the TSS for all genes whose TSS in included in a digest file. For instance
```
chr1:3735:COL11A1,chr1:3903:COL11A1:RING1B,chr1:4638:RNPC3
```
Do so as one additional column (i.e., column 15) in this format:
https://diachromatic.readthedocs.io/en/latest/digest.html

**Comment by pnrobinson** [comment]
This would need to be done in DigestCreationTask but information about the gene is not available in this class, and so this would require a relatively major rewrite of the code. @hansenp is this still something that we need or did we figure out how to do this in diachromatic directly?

**Comment by hansenp** [comment]
No, we don't need that at the moment.
