### ISSUE TITLE
Date sources prepare

### ISSUE THREAD

**Issue by WANGchuang715** [TheJacksonLaboratory/Gopher#373]
I noticed that the probe design required the GOPHER to download automatically by specifying the genome, and that the number of genomes that could be downloaded was limited.Can I pre-prepare the genome file myself instead of programmatically downloading it, for example, if I want to design a set of probes for pigs.
![image](https://user-images.githubusercontent.com/67625036/94355166-7612f800-00b4-11eb-9c53-5784189cfe4b.png)

**Comment by pnrobinson** [comment]
I think it would be difficult to do this without altering the source code of Gopher. If you are interested in a specific genome build for Pig we would just add this to the menu, that would be easier.

**Comment by pnrobinson** [comment]
@WANGchuang715  please reopen if it would be of interest to add the Pig build to the GUI.
