### ISSUE TITLE
Unable to paste gene symbols from clipboard

### ISSUE THREAD

**Issue by hansenp** [TheJacksonLaboratory/Gopher#387]
In the setup under 'Target gene list', gene symbols could be inserted either from the clipboard or from a text file. Now it is only possible from a text file. We should either reintroduce the clipboard feature or adjust the documentation accordingly.

**Comment by pnrobinson** [comment]
Let's adjust the documentation -- this feature is apparently not as easy to implement with the new version (we would need to do lots of refactoring)

**Comment by pnrobinson** [comment]
done
