### ISSUE TITLE
Display of hidden files when selecting a file

### ISSUE THREAD

**Issue by hansenp** [TheJacksonLaboratory/Gopher#389]
Hidden files are displayed in the input file selection dialog.

<img width="247" alt="image" src="https://user-images.githubusercontent.com/10495485/199782908-2ce4c740-3932-4579-94f3-eb7f7c07ea3a.png">

**Comment by pnrobinson** [comment]
I do not see any way of adding a negative filter to remove this, but we can add filters like this:

```
 FileChooser chooser = new FileChooser();
        chooser.setTitle("Open Gopher project file");
        chooser.getExtensionFilters().addAll(
                new FileChooser.ExtensionFilter("Gopher Files", "*.ser"));
        File file = chooser.showOpenDialog(null);
```
to only show files that have a certain extension.
I added this for the importing of previous Gopher projects. If there is another dialog that is showing too many irrelevant files please reopen with the name of the dialog
