### ISSUE TITLE
base-0 base-1 index error when exporting BED files

### ISSUE THREAD

**Issue by hansenp** [TheJacksonLaboratory/Gopher#390]
When I export the probes with 'Save BED file as' and view them in the UCSC Genome Browser, the probes are only 119 nt long. But they should be 120 nt long. This strongly suggests a base-0 base-1 index error in GOPHER.

<img width="1427" alt="image" src="https://user-images.githubusercontent.com/10495485/199789940-9f1269b9-28b4-442c-8bb0-581dd6c09d6f.png">

<img width="316" alt="image" src="https://user-images.githubusercontent.com/10495485/199790089-0dbab2cc-c53d-4e83-94c0-f6225d263426.png">

**Comment by pnrobinson** [comment]
It seems we cut off the first base
GATCGCTTTCCCAAGCAGGCAGGAATCTAAGTGTCCGGAAACGCCAGGAGCTGGCCGCCAGGTGAGCGGAGGACGAAGGGGTCCTGACTTCTAGGGGACAGGCCTTGGCAGCCGCTTTGA	1	+	chr1:16173718-16173837

in the all tracks fiule. The agilent file seems OK

TODO -- compare how both files generate the indices!
TODO -- look at the 3' end also -- do we have the same problem?

**Comment by pnrobinson** [comment]
In BEDFileExplorer, we have
```
 uniqueProbes.add(bait.getRefId() + "\t" + bait.getStartPos() + "\t" + bait.getEndPos() + "\tup|GC:" + String.format("%.2f",bait.getGCContent()) + "|Ali:" + String.format("%.2f",bait.getAlignabilityScore()) + "|Rep:" + String.format("%.2f",bait.getRepeatContent()) + "\t" + (int) Math.round(1000/bait.getAlignabilityScore()));
                    }
```
but in ProbeFileExporter, we have
```
(baitStartPosition - 1)
```

**Comment by pnrobinson** [comment]
@hansenp This is fixed in the latest version. Please check this and close if the bug is fixed!

**Comment by pnrobinson** [comment]
@hansenp I think this code is now correct, closing for release
