### ISSUE TITLE
Panel design summary is not saved with the project

### ISSUE THREAD

**Issue by hansenp** [TheJacksonLaboratory/Gopher#392]
If I create a design, save the project, close an reopen the GOPHER, then the panel design summary disappears from the analysis tab.

Before saving:
<img width="1197" alt="image" src="https://user-images.githubusercontent.com/10495485/200500862-b28c904f-86f7-43ef-a72d-0c6fb9f93c6a.png">

After reopening:
<img width="1197" alt="image" src="https://user-images.githubusercontent.com/10495485/200501116-d09c323c-2c0f-4093-a19c-2d0c64737622.png">

**Comment by pnrobinson** [comment]
fixed
