### ISSUE TITLE
0 unique transcription starts 

### ISSUE THREAD

**Issue by pnrobinson** [TheJacksonLaboratory/Gopher#393]
The summary that is obtained when setting up an experiment does not seem to capture the TSS data
```
Gene list | 31 chosen genes from 28278 in transcriptome
-- | --
Unique TSS | 0 unique transcription starts (from total of 42024)
```

**Comment by hansenp** [comment]
Please provide more information so that it is possible to reproduce and understand the bug.

**Comment by pnrobinson** [comment]
I cannot seem to reproduce this error, it must have been something that happened in some development phase.
