### ISSUE TITLE
Allow for target positions beyond TSS

### ISSUE THREAD

**Issue by hansenp** [TheJacksonLaboratory/Gopher#66]

**Comment by hansenp** [comment]
Another potential user is asking for this feature:

> I am not doing a promoter capture, but a capture of a 5Mb region that I want to completely cover with probes.

**Comment by pnrobinson** [comment]
We could probably implement a Bed file importer? That would be good for multiple use cases. But if they just want 5 MB, maybe they should just go ahead and order?

**Comment by hansenp** [comment]
No, they want to enrich for the margins only.

**Comment by hansenp** [comment]
For now I found the following workaround:

1. Unzip `refGene.txt.gz`.
2. Add lines for non-TSS target positions. Relevant fields in `refGene.txt` are: reference ID (3), strand (4), position (5), name of target (13).
3. Compress `refGene.txt`.
4. Create a file `genelist.txt`. The names correspond to the names of targets in `refGene.txt.gz`.
5. Open VPC. For the _Transcripts_ select the directory that contains the prepared `refGene.txt.gz` file.
6. For _Enter gene list_ select the prepared `genelist.txt`.

**Comment by hansenp** [comment]
The implementation should be straight forward:
1. On the set up tab, provide an additional button _Upload_ for _User defined targets_, which can be used to upload a BED file.
2. Write a function that parses the BED file similar to `RefGeneParser.parse(path)`.

**Comment by pnrobinson** [comment]
We could also easily implement a BED importer. We would require six fields
```
chrom
chromStart
chromEnd
name
score 
strand
````
We could then create a GopherGene object from this . We could initialze the geneSymbol and the refseqId in GopherGene to both be the string in the name column. We would ignore the "score". The strand would not be important if we are talking about only SNPs, but we should leave it in case people want to enrich enhancers or other items which might have a strand.

**Comment by hansenp** [comment]
This is an important feature and your suggestion for implementation sounds good. However, I'm not sure if this collides with our goal make a new release and to write up the manuscript within the next one or two weeks.

**Comment by pnrobinson** [comment]
I think this is basically only one hour of work, so let's include it, OK?

**Comment by hansenp** [comment]
ok

**Comment by pnrobinson** [comment]
This could be the format

```
chr16   31357553        31357553        rs11574637     0          +         
chr18   71175007        71175007        rs17083844     0          +
chr1     71808790        71808790        rs12141391     0          +
chr2     191099907      191099907      rs7574865       0          +
chr5     42375141        42375141         rs979233         0          +
chr6     32638107        32638107         rs2187668       0          +​
```

**Comment by pnrobinson** [comment]
This is now working @hansenp 
However, some of the viewpoints are not getting selected because of the filter criteria. This can be regarded as a feature or as a bug, but I guess it is OK if we tell the user in the manual to set the filter criteria such that there is no filtering (e.g., GC=0 to 100).

**Comment by pnrobinson** [comment]
TODO--adjust the labels shown on the VPVGene panel!

**Comment by pnrobinson** [comment]
This is now working -- I have tested it with the GWAS hits and all hits are appearing. The label is not ideal because we have things like rs979233[rs979233], but I think it is hard to do much better because we do no know exactly what the BED file names will look like. I will therefore close this issue for now. We can wait and see if users want us to do more for specific situations.
