### ISSUE TITLE
Import gene symbols via text file not user friendly

### ISSUE THREAD

**Issue by hansenp** [TheJacksonLaboratory/Gopher#67]

**Comment by pnrobinson** [comment]
I am wondering if we can do this with a text area (roughly http://tutorials.jenkov.com/javafx/textarea.html) and also using the System clipboard -- if the user presses the "paste" button, then it would append the text to the end of the list. We could add a button to open a copy paste editor or something.

**Comment by hansenp** [comment]
Maybe this text area could appear in this window as a third option.

![image](https://user-images.githubusercontent.com/10495485/42994285-f4ccf51a-8c0d-11e8-9330-e76b44b337d3.png)

**Comment by hansenp** [comment]
Cool! But if I click on _Clipboard_, nothing happens. Furthermore, I would switch the _Accept_ and _Cancel_ button, because it's more intuitive to go from left to right.

![image](https://user-images.githubusercontent.com/10495485/43064257-add4edea-8e5e-11e8-856a-bf7b477b7c9b.png)

**Comment by pnrobinson** [comment]
Clipboard only does something if you have previously copied something to the system clipboard, otherwise nothing happens.
I will switch the order

**Comment by pnrobinson** [comment]
Fixed this!
