### ISSUE TITLE
VPV documentation incomplete

### ISSUE THREAD

**Issue by hannahblau** [TheJacksonLaboratory/Gopher#94]
replace all TODO items with text (too numerous to list individual pages)

**Comment by hannahblau** [comment]
Documentation refers to VSV in many places, is this a typo for VPV? or the German translation of VPV? Anyway, it's confusing. I would either eliminate all occurrences of VSV or explain what it means.

**Comment by hannahblau** [comment]
I don't see anything in the documentation about the top level menu items Proxy, Log, Exome, Report. These should be documented.

**Comment by hannahblau** [comment]
Significance of different colors in the Show Log window is not clear.
TRACE black, blue, purple, red
DEBUG black, blue, red
INFO black, red
WARN red
ERROR red

**Comment by hannahblau** [comment]
What does (*) signify after the location of a fragment in the viewpoint detail pane? Not mentioned in doc as far as I can tell.

**Comment by hannahblau** [comment]
Screenshot of panel design window does not quite match how the window looks now in the software, should be updated to sync with the software. See attached file for screenshot of how the window looks now.
![paneldesignwindow](https://user-images.githubusercontent.com/8484992/32974502-a3e6fc42-cbcc-11e7-9747-3c8edbb863e7.png)

**Comment by hannahblau** [comment]
Buttons in the viewpoint window (zoom in, zoom out, delete, copy URL, close) are not explained in documentation. Close is obvious, but are the others? This delete button does the same thing as the delete button in the panel design window, right? Is copy URL self-evident to people who are more familiar than I with the UCSC genome browser? See issue #104 about zoom in and zoom out.

**Comment by pnrobinson** [comment]
Corrected the type "VSV".

**Comment by pnrobinson** [comment]
I am going to close this now -- as a result of some new ideas, we will be adding some new functions and re-doing the documentation over the next month or two. We will complete the documentation at that stage.
