### ISSUE TITLE
Add flags to show whether a Viewpoint was manually revised or checked

### ISSUE THREAD

**Issue by hansenp** [TheJacksonLaboratory/Gopher#98]
If I
1. Set up a project
2. Set all parameters and the approach parameter to Extended
3. Create the viewpoints
4. Save the project
5. Reopen the project
then the approach switches back to simple.

**Comment by pnrobinson** [comment]
Yes, I do not think we are explicitly storing the approach in Model right now. Should we do so? And also add a flag, "Manual" if the user changes anything (this would be per viewpoint and would not affect the overall approach). One thing is that it would be harded to keep track of whether the user just tries out a new fragment and then deletes it, so that the viewpoint is unchanged. If we agree that we still mark that as manual, then it is easy.

**Comment by hansenp** [comment]
> Yes, I do not think we are explicitly storing the approach in Model right now. Should we do so?

Yes, I would do it like this.

We should definitely have the "Manual" flag. I would suggest to start with the easy implementation, and to create an (enhancement) issue for the problem with edited but unchanged viewpoints.

**Comment by pnrobinson** [comment]
@hansenp Added code to make the approach be saved and shown when a project is reopened.
Note that this will not work immediately with saved model files, but it will work if you do something and save a project from now on.

**Comment by pnrobinson** [comment]
Still to do: Add flags to show whether a Viewpoint was manually revised or checked.

**Comment by pnrobinson** [comment]
I think that this feature is actually pretty difficult to get right and would add a lot of complexity, unless we do not care whether the user returns the viewpoint to the original state after trying out some changes.

**Comment by hansenp** [comment]
I think we would need the equals function for Viewpoint objects. Then we could create/copy a temporary Viewpoint object when the first edit is made. Before saving we use the equals function in order to decide if the viewpoint really changed. If this is the case, we set the flag to manual otherwise not. We could define two Viewpoint objects to be equal, if they have the same set of active digests.

**Comment by pnrobinson** [comment]
@hansenp  -- we need to decide what the desired functionality is. Your last comment seems to say you want to show if the viewpoint was manually changed. If so, then the best things would be to add undo/redo functionality using the command pattern -- see http://www.algosome.com/articles/implementing-undo-redo-java.html
If the stack is empty, then even if the user has worked on the viewpoint, we can say that it is the same as originally. If the stack is not empty, then the viewpoint is not the same. The stack would record the commands the change the viewpoint (adding or removing fragments). Alternatively, we could just store the original fragments somewhere, that would not add a lot of memory.

On the other hand, if we just want to record if the user is satisfied with a viewpoint, then the current checkmark will do it, and we would just need to add something like a save button to the ViewPoint panel.

**Comment by pnrobinson** [comment]
This is working now.
